/**
 * @file menuFight.c
 * @brief menuFight -- XD translation unit: overworld NPC "fight menu" UI
 *        (item/money/quest/mart/trainer-battle bridge, secret-base status
 *        menus, target selection, waza/move-tutor, purification, warp).
 *
 * Address range: 0x8000DAA8 - 0x80011B4C (46 functions)
 *
 * Split from game/gs_npc_interact.c (a CodeCandidate bucket spanning two
 * XD-era translation units) into its true source file. See
 * game/menuFightStatus.c for the sibling TU (0x80011B4C-0x80011EA4) that
 * used to share this bucket; in XD, menuFightStatus.cpp links immediately
 * after menuFight.cpp, but in Colosseum's link order they occupy the same
 * CodeCandidate range, so the split follows the high-confidence boundary
 * at 0x80011B4C (see split rationale in the naming-pass notes).
 *
 * fn_8000D710 is physically included at the top of this file even though
 * its address (0x8000D710) sits just below this TU's declared start; it
 * belongs to the preceding range unit (game/gs_range_8000D290.c) and is
 * carried over unmodified from the original monolithic file pending a
 * follow-up boundary fix.
 */

#include "dolphin/types.h"

/* =========================================================================
 * External declarations
 * ========================================================================= */

/* renamed symbols referenced by asm incs (symbolmap port) */
extern u32 _menuFightIsUse__FP16MENU_WAZA_STATUSUs();
extern void* menuSubCalcColor(void*, void*);

/* NPC/People system */
extern void  winSpriteSetDisp(void* npc, s32 direction);  /* Set NPC facing */
extern void* menuItemBiosGetPtr(s16 npcId);                  /* Lookup NPC data by ID */

/* Text/dialog system */
extern void  windowDrawSprite();
extern void  winSeqSetMenu(void* ctx, s32 state);       /* Set dialog state */
extern void  fn_801081F8(void* ctx, s32 msgId, s32 flags); /* Display message */

/* Rendering */
extern u32   GSmsgGetRect();                           /* Get model dimensions */
extern void  fn_800FB680();

/* Map/warp */
extern u8    fightFloorCheckFightActionFightOutPokemonIrekaeSelect(s32 p1, void* warpId, void* outDest);
extern void* fightOutPokemonGetNicknamePtr(void* mapData);              /* Get map name string */
extern void  winMsgOpen(s32 slot, s32 msgId, s32 p3, s32 p4);
extern void  winMsgClose(s32 slot);                   /* Close message box */

/* Input/frame */
extern u8    fn_801F18DC(s32 controller);             /* Check input ready */
extern u8    fightFloorIsUseFightTimerCommand(s32 controller);             /* Check button pressed */
extern u8    fightTimerCommandIsOver(void);                       /* Check A button */
extern u16   fn_801EF634(void);                       /* Get input state */
extern void  _threadSwitch(void);                       /* Frame advance */
extern u32   fn_800F7AF0(s32 slot);                   /* Get render flags */
extern u32   fn_800F7BC4(s32 slot);                   /* Get VSync flags */

/* Battle bridge */
extern void  msgctrlSetValue();                           /* Set battle parameter */
extern void  fightFloorSetStatus();                           /* Configure map object */
extern u32   windowGetParam();                           /* Get participant data */

/* =========================================================================
 * SDA globals
 * ========================================================================= */

/* NPC interaction state variables are scattered across the SDA region.
 * The exact mapping is determined by the lbz/sth instructions that
 * reference r0+offset or r13+offset addressing modes. */

/* ===================================================================
 * AUTO-GENERATED accessor functions
 * Generated by tools/gen_accessors.py
 * 1 functions matched
 * =================================================================== */

extern u8 lbl_8047A2A0;

/* Address: 0x8000DAA8 | Size: 0x8 | Pattern: sda_getter */
u8 fn_8000DAA8(void) {
    return lbl_8047A2A0;
}

/* =========================================================================
 * Stubs for remaining GSnpcInteract functions (0x800111C4-0x80011EA4)
 * ========================================================================= */

/* 0x800111C4 | 0x24 -- small accessor */
extern void fn_80089F78(u32, u32, u32, u32);
#if 0
asm void menuFightOpenGBAMain(void) {
#include "src/game/gs_npc_interact_fn_800111C4.inc"
}
#else
#pragma peephole off
void menuFightOpenGBAMain(u32 a, u32 b, u32 c) { fn_80089F78(a, b, c, 0); }
#pragma peephole on
#endif

/* 0x800111E8 | 0x24 -- small accessor */
#if 0
asm void menuFightOpenGBAIrekae(void) {
#include "src/game/gs_npc_interact_fn_800111E8.inc"
}
#else
#pragma peephole off
void menuFightOpenGBAIrekae(u32 a, u32 b, u32 c) { fn_80089F78(a, b, c, 1); }
#pragma peephole on
#endif

/* 0x7C | menuFightCloseTarget | nullcheck_call_flag */
#pragma peephole off
u32 menuFightCloseTarget(void* obj) {
    extern void menuCloseCustom();
    if ((u8)menuIsCheck(0xff) != 0) menuCloseCustom(0xff, 0, obj);
    if ((u8)menuIsCheck(0x104) != 0) menuCloseCustom(0x104, 0, obj);
    menuIsCheck(0x100);
    return 0;
}
#pragma peephole on

/* 0x80011288 | 0x21C */
extern void menuItemBiosSetSelectFlag();
extern void menuGetCursorFromItemID();
extern s32 menuOpenCustom(s32, ...);
#if 0
asm void menuFightOpenTarget(void) {
#include "src/game/gs_npc_interact_fn_80011288.inc"
}
#else
void menuFightOpenTarget(void) {
    extern void menuItemBiosSetSelectFlag();
    extern void menuGetCursorFromItemID();
    extern void menuOpenCustom();
    u8 sp[0x20];
    u32 tmp = 0;
    u32 r3 = 0;
    u32 r4 = 0;
    u32 r5 = 0;
    u32 r6 = 0;
    u32 r7 = 0;
    u32 r8 = 0;
    u32 r9 = 0;
    u32 r28 = 0;
    u32 r29 = 0;
    u32 r30 = 0;
    u32 r31 = 0;

    r28 = r3;
    r29 = r5;
    tmp = *(u8*)((u8*)r28 + 0x21);
    if (tmp == 0) {
    do {
        r3 = 0x1258;
        r4 = 0x0;
        menuItemBiosSetSelectFlag();
        r3 = 0x1259;
        r4 = 0x0;
        menuItemBiosSetSelectFlag();
        r3 = 0x125a;
        r4 = 0x0;
        menuItemBiosSetSelectFlag();
        r3 = 0x125b;
        r4 = 0x0;
        menuItemBiosSetSelectFlag();
        r31 = r28;
        r30 = 0x0;
        do {
        do {
            tmp = *(u32*)((u8*)r31 + 0x4);
            if ((s32)tmp != 0x47) {
                if ((s32)tmp < 0x47) {
                    if ((s32)tmp != 0x45) {
                        if ((s32)tmp < 0x45) {
                            goto L_8001133C;
                        }
                        if ((s32)tmp >= 0x49) goto L_8001133C;
                        goto L_80011334;
                        }
                    r3 = 0x125b;
                    break;
                        }
                r3 = 0x125a;
                break;
            }
            r3 = 0x1258;
            break;
        L_80011334:
            r3 = 0x1259;
            break;
        L_8001133C:
            r3 = 0x0;
        } while (0);
            if ((s32)r3 != 0) {
                r4 = 0x1;
                menuItemBiosSetSelectFlag();
            }
            r31 = r31 + 0x8;
            r30 = r30 + 0x1;
        } while ((s32)r30 < 4);
        r3 = 0xff;
        r4 = 0x125a;
        menuGetCursorFromItemID();
        if ((s32)r3 == (s32)-0x1) {
            r3 = 0xff;
            r4 = 0x125b;
            menuGetCursorFromItemID();
            if ((s32)r3 == (s32)-0x1) {
                tmp = 0x0;
                *(u32*)(sp + 0x8) = tmp;
        }
        }
        r7 = r29;
        r9 = r28;
        r5 = (u32)sp + 0x8;
        r3 = 0xff;
        r4 = 0x0;
        r6 = 0x0;
        r8 = 0x1;
        menuOpenCustom();
        if ((s32)r3 != 0x125a) {
            if ((s32)r3 < 0x125a) {
                if ((s32)r3 != 0x1258) {
                    if ((s32)r3 < 0x1258) {
                        goto L_80011404;
                    }
                    if ((s32)r3 >= 0x125c) goto L_80011404;
                    goto L_800113FC;
                    }
                r4 = 0x47;
                break;
                    }
            r4 = 0x48;
            break;
        }
        r4 = 0x46;
        break;
    L_800113FC:
        r4 = 0x45;
        break;
    L_80011404:
        r4 = -0x1;
    } while (0);
        r3 = -0x1;
        tmp = *(u32*)((u8*)r28 + 0x4);
        if ((s32)r4 == (s32)tmp) {
            r3 = 0x0;
            return;
        }
        tmp = *(u32*)((u8*)r28 + 0xC);
        if ((s32)r4 == (s32)tmp) {
            r3 = 0x1;
            return;
        }
        tmp = *(u32*)((u8*)r28 + 0x14);
        if ((s32)r4 == (s32)tmp) {
            r3 = 0x2;
            return;
        }
        tmp = *(u32*)((u8*)r28 + 0x1C);
        if ((s32)r4 != (s32)tmp) return;
        r3 = 0x3;
        return;
        return;
    }
    r5 = r4;
    r7 = r29;
    r9 = r28;
    r3 = 0x104;
    r4 = 0x0;
    r6 = 0x0;
    r8 = 0x1;
    menuOpenCustom();

    return;
}
#endif

/* 0x800114A4 | 0x25C */
extern void fightTypeDataBiosGetPtr();
extern void fightTypeDataBiosGetFightoutPokemonNum();
extern void menuPokemonOpenFight();
extern void menuCloseCustom();
extern void fightTargetGetPtr();
extern void fightOutPokemonCheckFightOut();
extern void fightMenuGetFightOutPokemonPtrToStatusMenuId();
extern u32 menuPokemonCheckPokemonChange();
extern void menuFightOpenTarget();
#if 0
asm void menuFightOpenPokemon(void) {
#include "src/game/gs_npc_interact_fn_800114A4.inc"
}
#else
void menuFightOpenPokemon(void) {
    extern u32 menuPokemonCheckPokemonChange();
    extern void menuFightOpenTarget();
    extern void menuPokemonOpenFight();
    extern void menuCloseCustom();
    extern void menuIsCheck();
    extern void menuOpenCustom();
    extern void fightTargetGetPtr();
    extern void fightOutPokemonCheckFightOut();
    extern void fightTypeDataBiosGetFightoutPokemonNum();
    extern void fightTypeDataBiosGetPtr();
    extern void fightMenuGetFightOutPokemonPtrToStatusMenuId();
    u8 sp[0x60];
    u32 tmp = 0;
    u32 r3 = 0;
    u32 r4 = 0;
    u32 r5 = 0;
    u32 r6 = 0;
    u32 r7 = 0;
    u32 r8 = 0;
    u32 r9 = 0;
    u32 r10 = 0;
    u32 r23 = 0;
    u32 r24 = 0;
    u32 r25 = 0;
    u32 r26 = 0;
    u32 r27 = 0;
    u32 r28 = 0;
    u32 r29 = 0;
    u32 r30 = 0;
    u32 r31 = 0;
    f32 f8 = 0.0f;

    r24 = r3;
    r25 = r4;
    r26 = r5;
    r27 = r6;
    r28 = r7;
    r3 = r26;
    fightTypeDataBiosGetPtr();
    fightTypeDataBiosGetFightoutPokemonNum();
    tmp = r28 & 0xFF;
    r31 = r3;
    if (tmp == 0) {
        r4 = r27;
        r5 = r24;
        r6 = r25;
        menuPokemonOpenFight();
        r29 = r3;
        r3 = r29;
        return;
    }
    r30 = r27 & 0xFF;
L_80011500:
    r3 = 0xf8;
    r4 = 0x1e;
    ((void(*)(void))winSeqSetMenu)();
    r9 = r24;
    r10 = r25;
    r3 = 0xf8;
    r4 = 0x0;
    r5 = 0x0;
    r6 = 0x0;
    r7 = 0x1;
    r8 = 0x3;
    menuOpenCustom();
    tmp = r3;
    r3 = 0xf8;
    r29 = tmp;
    r4 = 0x20;
    ((void(*)(void))winSeqSetMenu)();
    if ((s32)r29 == (s32)-0x1) {
        r3 = 0xf8;
        r4 = 0x0;
        r5 = 0x1;
        menuCloseCustom();
        r3 = -0x1;
        return;
    }
    r3 = r25;
    r4 = r24;
    r5 = r29;
    menuPokemonCheckPokemonChange();
    tmp = r3 & 0xFF;
    if (tmp == 0) goto L_80011500;
    tmp = r27 & 0xFF;
    do {
        if (tmp == 0) break;
        tmp = r31 & 0xFF;
        if (tmp < 2) break;
        r4 = r25;
        r5 = r26;
        r3 = 0xf;
        fightTargetGetPtr();
        r23 = r3;
        fightOutPokemonCheckFightOut();
        tmp = r3 & 0xFF;
        if (tmp == 1) {
            r3 = r23;
            r4 = r26;
            r5 = 0x0;
            fightMenuGetFightOutPokemonPtrToStatusMenuId();
        } else {

            r3 = 0x0;
        }
        r4 = r25;
        r5 = r26;
        r3 = 0x10;
        fightTargetGetPtr();
        r23 = r3;
        fightOutPokemonCheckFightOut();
        tmp = r3 & 0xFF;
        if (tmp == 1) {
            r3 = r23;
            r4 = r26;
            r5 = 0x0;
            fightMenuGetFightOutPokemonPtrToStatusMenuId();
        } else {

            r3 = 0x0;
        }
        r4 = r25;
        r5 = r26;
        r3 = 0xe;
        fightTargetGetPtr();
        r23 = r3;
        fightOutPokemonCheckFightOut();
        tmp = r3 & 0xFF;
        if (tmp == 1) {
            r3 = r23;
            r4 = r26;
            r5 = 0x0;
            fightMenuGetFightOutPokemonPtrToStatusMenuId();
        } else {

            r3 = 0x0;
        }
        tmp = 0x0;
        r3 = (u32)sp + 0x10;
        r4 = 0x0;
        *(u32*)(sp + 0x2C) = tmp;
        r5 = 0x1;
        *(u8*)(sp + 0x31) = r28;
        menuFightOpenTarget();
        r23 = r3;
        r3 = 0xff;
        menuIsCheck();
        tmp = r3 & 0xFF;
        if (tmp != 0) {
            r3 = 0xff;
            r4 = 0x0;
            r5 = 0x1;
            menuCloseCustom();
        }
        r3 = 0x104;
        menuIsCheck();
        tmp = r3 & 0xFF;
        if (tmp != 0) {
            r3 = 0x104;
            r4 = 0x0;
            r5 = 0x1;
            menuCloseCustom();
        }
        r3 = 0x100;
        menuIsCheck();
        if ((s32)r23 == (s32)-0x1) goto L_80011500;
    } while (0);

    r3 = 0xf8;
    r4 = 0x0;
    r5 = 0x1;
    menuCloseCustom();

    r3 = r29;

    return;
}
#endif

/* 0x80011700 | 0xBC - clear 4 event flags referenced by input arg */
#if 0
asm void menuFightCloseWaza(void) {
#include "src/game/gs_npc_interact_menuFightCloseWaza.inc"
}
#else
#pragma push
#pragma peephole off
s32 menuFightCloseWaza(s32 arg) {
    if ((u8)menuIsCheck(0x4c) != 0) menuCloseCustom(0x4c, 0, arg);
    if ((u8)menuIsCheck(0xf9) != 0) menuCloseCustom(0xf9, 0, arg);
    if ((u8)menuIsCheck(0xfa) != 0) menuCloseCustom(0xfa, 0, arg);
    if ((u8)menuIsCheck(0xf7) != 0) menuCloseCustom(0xf7, 0, arg);
    return 0;
}
#pragma pop
#endif

/* 0x800117BC | 0x1EC */
extern void winMsgOpenFight();
extern void winMsgCloseFight();
#if 0
asm void menuFightOpenWaza(void) {
#include "src/game/gs_npc_interact_fn_800117BC.inc"
}
#else
s32 menuFightOpenWaza(void* arg0, void* arg1, void* arg2) {
    extern u32 _menuFightIsUse__FP16MENU_WAZA_STATUSUs();
    extern void menuCloseCustom();
    extern void menuIsCheck();
    extern void menuOpenCustom();
    extern void winMsgCloseFight();
    extern void winMsgOpenFight();
    u8 sp[0x20];
    u32 tmp = 0;
    u32 r3 = (u32)arg0;
    u32 r4 = (u32)arg1;
    u32 r5 = (u32)arg2;
    u32 r6 = 0;
    u32 r7 = 0;
    u32 r8 = 0;
    u32 r9 = 0;
    u32 r26 = 0;
    u32 r27 = 0;
    u32 r28 = 0;
    u32 r29 = 0;
    u32 r30 = 0;
    u32 r31 = 0;
    f32 f7 = 0.0f;
    f32 f9 = 0.0f;

    r28 = r3;
    r29 = r4;
    r30 = r5;
    tmp = *(u8*)((u8*)r28 + 0x44);
    if (tmp == 0) {
        r31 = 0x4c;

    } else {
        r31 = 0xf7;
    }
L_800117F0:
    r3 = r31;
    r4 = 0x1e;
    ((void(*)(void))winSeqSetMenu)();
    r3 = r31;
    r5 = r29;
    r7 = r30;
    r9 = r28;
    r4 = 0x0;
    r6 = 0x0;
    r8 = 0x1;
    menuOpenCustom();
    r27 = r3;
    do {
        if ((s32)r27 < 0) break;
        r3 = r28;
        r4 = r27 & 0xFFFF;
        _menuFightIsUse__FP16MENU_WAZA_STATUSUs();
        r26 = r3;
        if (r26 == 0) break;
        r3 = 0x4c;
        menuIsCheck();
        tmp = r3 & 0xFF;
        if (tmp != 0) {
            r3 = 0x4c;
            r4 = 0x0;
            r5 = 0x1;
            menuCloseCustom();
        }
        r3 = 0xf9;
        menuIsCheck();
        tmp = r3 & 0xFF;
        if (tmp != 0) {
            r3 = 0xf9;
            r4 = 0x0;
            r5 = 0x1;
            menuCloseCustom();
        }
        r3 = 0xfa;
        menuIsCheck();
        tmp = r3 & 0xFF;
        if (tmp != 0) {
            r3 = 0xfa;
            r4 = 0x0;
            r5 = 0x1;
            menuCloseCustom();
        }
        r3 = 0xf7;
        menuIsCheck();
        tmp = r3 & 0xFF;
        if (tmp != 0) {
            r3 = 0xf7;
            r4 = 0x0;
            r5 = 0x1;
            menuCloseCustom();
        }
        r3 = r26;
        r4 = 0x1;
        r5 = 0x1;
        winMsgOpenFight();
        while (1) {
            r3 = 0x1;
            ((void(*)(void))fn_800F7AF0)();
            r27 = r3;
            r3 = 0x1;
            ((void(*)(void))fn_800F7BC4)();
            tmp = r3 & r27;
            tmp = tmp & 0x00000300;
            if (tmp != 0) break;
            r3 = 0x0;
            ((void(*)(void))fn_801F18DC)();
            tmp = r3 & 0xFF;
            do {
                if (tmp == 0) break;
                r3 = 0x0;
                ((void(*)(void))fightFloorIsUseFightTimerCommand)();
                tmp = r3 & 0xFF;
                do {
                    if (tmp != 1) break;
                    ((void(*)(void))fightTimerCommandIsOver)();
                    tmp = r3 & 0xFF;
                    if (tmp != 1) break;
                    tmp = 0x1;
                    break;
                } while (0);

                ((void(*)(void))fn_801EF634)();
                tmp = r3 & 0xFFFF;
                if (tmp != 1) break;
                tmp = 0x1;
                break;
            } while (0);

            tmp = 0x0;

            tmp = tmp & 0xFF;
            if (tmp != 0) break;
            ((void(*)(void))_threadSwitch)();

        }

        r3 = 0x1;
        winMsgCloseFight();
        goto L_800117F0;
    } while (0);

    r3 = r31;
    r4 = 0x20;
    ((void(*)(void))winSeqSetMenu)();
    r3 = r27;
    return;
}
#endif

/* 0x74 | menuFightCloseTop | nullcheck_call_flag */
#pragma peephole off
#pragma peephole off
u32 menuFightCloseTop(void* obj) {
    if ((u8)menuIsCheck(0x4b) != 0) menuCloseCustom(0x4b, 0, obj);
    if ((u8)menuIsCheck(0xf6) != 0) menuCloseCustom(0xf6, 0, obj);
    return 0;
}
#pragma peephole on
#pragma peephole on

/* 0x80011A1C | 0x130 */
#if 0
asm void fn_80011A1C(void) {
#include "src/game/gs_npc_interact_fn_80011A1C.inc"
}
#else
#pragma push
#pragma peephole off
s32 fn_80011A1C(u8* obj, s32 a1, s32 a2) {
    u32 sp8;
    s32 ret;    /* r30 */
    u8 locked;  /* r29 */
    s32 ret2;   /* r31 */

    locked = obj[0x16];
    do {
        if (obj[0x17] != 0) {
            ret = menuOpenCustom(0xF6, 0, a1, 0, a2, 1, obj);
        } else {
            ret = menuOpenCustom(0x4B, 0, a1, 0, a2, 1, obj);
        }
        if (locked != 0) break;
        if (ret != 3) break;
        sp8 = 0;
        if ((u8)menuIsCheck(0x4B) != 0) {
            menuCloseCustom(0x4B, 0, 1);
        }
        if ((u8)menuIsCheck(0xF6) != 0) {
            menuCloseCustom(0xF6, 0, 1);
        }
        ret2 = menuOpenCustom(0xFB, 0, &sp8, 0, 1, 0);
        menuCloseCustom(0xFB, 0, 1);
    } while (ret2 != 0x1207);

    return ret;
}
#pragma pop
#endif

/* ===== Phase 2 recovery stubs ===== */

/* fn_8000D710 - 0x8000D710 | size: 0x398 */
extern s32 heroMoveCheckEvent();
extern void fn_80116D30(void);
extern void heroMoveInitEvent(void);
extern void mailMainReceiveTerminate(void);
extern void GSmodelAllPauseAnimation(void);
extern s32 fn_800D37CC();
extern void menuCreateOffScreen(void);
extern u8 menuGetOffScreenFlag();
extern void fn_801661D0(void);
extern void fn_800D3074(void);
extern void* fn_801906A0();
extern u32 fn_800FF560();
extern void fn_80130CD8(void);
extern void GSgappBlock(void);
extern void GSthreadBlockGroup(void);
extern void GSthreadCreate(void);
extern void GSgappUnblock(void);
extern void menuClose();
extern void GSmodelAllUnpauseAnimation(void);
extern void menuPokemonOpen(void);
extern void menuPdaOpen(void);
extern u32 fn_80018F88();
extern u32 fn_80019070();
extern void heroMoveAddAutoEvent(void);
extern s32 fn_801CBAB8();
extern void menuOffScreenRelease(void);
extern void fn_801660D8(void);
extern void menuReleaseOffScreen(void);
extern void menuCloseSync(void);
extern void heroMoveTermEvent(void);
extern u8 lbl_8047A2A0;
extern u32 lbl_8047B6F8;
extern f32 lbl_8047B6F0;
extern u32 lbl_8047A2A4;
extern u32 lbl_8047A2A8;
extern u32 lbl_8047A2AC;
extern u32 lbl_8047A2B0;
u32 fn_8000DAB0(void); /* forward decl: referenced by fn_8000D710 asm inc */
#if 0
asm void fn_8000D710(void) {
#include "src/game/gs_npc_interact_fn_8000D710.inc"
}
#else
#pragma push
#pragma peephole off
u32 fn_8000D710(u32 mode) {
    extern s32 heroMoveCheckEvent(void* out);
    extern void fn_80116D30(s32 kind, u16 value);
    extern void heroMoveInitEvent(void);
    extern void mailMainReceiveTerminate(void);
    extern void GSmodelAllPauseAnimation(void);
    extern s32 fn_800D37CC(void);
    extern void menuCreateOffScreen(f32 value);
    extern u8 menuGetOffScreenFlag(void);
    extern void fn_801661D0(s32, s32, s32, s32);
    extern void fn_800D3074(s32);
    extern void* fn_801906A0(s32);
    extern u32 fn_800FF560(void);
    extern void fn_80130CD8(void);
    extern void GSgappBlock(void);
    extern void GSthreadBlockGroup(u32);
    extern void GSthreadCreate(s32, void*, u32, s32, s32, void*);
    extern void GSgappUnblock(void);
    extern void menuClose(s32);
    extern void GSmodelAllUnpauseAnimation(void);
    extern void menuPokemonOpen(s32, s32, s32);
    extern void menuPdaOpen(void);
    extern u32 fn_80018F88(s32, void*, s32);
    extern u32 fn_80019070(u32);
    extern void heroMoveAddAutoEvent(u32, u32, u32, s32, s32);
    extern s32 fn_801CBAB8(void);
    extern void menuOffScreenRelease(void);
    extern void fn_801660D8(s32, s32, s32);
    extern void menuReleaseOffScreen(f32 value);
    extern void menuCloseSync(s32, s32);
    extern void heroMoveTermEvent(void);
    extern f32 lbl_8047B6F0;
    u8 stackData[0xD8];
    void* threadEntry;
    s32 count;
    s32 i;
    s32 dialogId;
    u16 result;
    u32 work;
    u32 tmp;

    count = heroMoveCheckEvent(stackData);
    for (i = 0; i < count; i++) {
        fn_80116D30(4, *(u16*)(stackData + 0x30 + (i * 0x34)));
    }

    heroMoveInitEvent();
    mailMainReceiveTerminate();
    _threadSwitch();
    GSmodelAllPauseAnimation();
    lbl_8047A2A0 = 1;
    tmp = fn_800D37CC();
    if (tmp != 0) {
        menuCreateOffScreen(lbl_8047B6F0 / (f32)(s32)tmp);
    }
    while ((u8)menuGetOffScreenFlag() == 0) {
        _threadSwitch();
    }
    fn_801661D0(0x55, 0x1F4, 1, 1);
    fn_800D3074(1);
    dialogId = (fn_801906A0(0x8AE) == NULL) ? 0x41 : 0x109;
    result = 0;

    switch ((u8)mode) {
    case 0:
        threadEntry = (void*)fn_8000DAB0;
        do {
            fn_800D3074(1);
            lbl_8047A2A4 = dialogId;
            lbl_8047A2A8 = fn_800FF560();
            fn_80130CD8();
            GSgappBlock();
            GSthreadBlockGroup(lbl_8047A2A8);
            lbl_8047A2AC = lbl_8047A2A8 - 0x20;
            GSthreadCreate(0xF, (void*)lbl_8047A2AC, 0x4000, 1, 1, threadEntry);
            _threadSwitch();
            fn_80130CD8();
            GSgappUnblock();

            if (lbl_8047A2B0 == 0) {
                menuClose(dialogId);
                GSmodelAllUnpauseAnimation();
                menuPokemonOpen(1, 0, 0);
                GSmodelAllPauseAnimation();
            } else if (lbl_8047A2B0 == 1) {
                menuClose(dialogId);
                GSmodelAllUnpauseAnimation();
                menuPdaOpen();
                GSmodelAllPauseAnimation();
            } else if (lbl_8047A2B0 == 2) {
                menuClose(dialogId);
                GSmodelAllUnpauseAnimation();
                result = fn_80018F88(0, &work, 0);
                GSmodelAllPauseAnimation();
                if (((u16)result != 0) && (fn_80019070(result) != 0xFFFFFFFF)) {
                    heroMoveAddAutoEvent(fn_80019070(result), (u16)result, work, 0, 0);
                    break;
                }
            } else {
                break;
            }
        } while (1);
        break;
    case 1:
        result = fn_80018F88(0, &work, 0);
        if (((u16)result != 0) && (fn_80019070(result) != 0xFFFFFFFF)) {
            heroMoveAddAutoEvent(fn_80019070(result), (u16)result, work, 0, 0);
        }
        break;
    default:
        break;
    }

    fn_80019070(result);
    fn_801660D8(0x1F4, 1, 1);
    menuClose(dialogId);
    tmp = fn_800D37CC();
    if (tmp != 0) {
        menuReleaseOffScreen(lbl_8047B6F0 / (f32)(s32)tmp);
    }
    menuCloseSync(dialogId, 1);
    fn_800D3074(2);
    heroMoveTermEvent();
    GSmodelAllUnpauseAnimation();
    lbl_8047A2A0 = 0;
    return 0;
}
#pragma pop
#endif

/* fn_8000DAB0 - 0x8000DAB0 | size: 0x38 */
extern u32 menuOpen(u32, u32);
extern void GSthreadUnblockGroup(u32);
extern u32 lbl_8047A2A4;
extern u32 lbl_8047A2A8;
extern u32 lbl_8047A2B0;
#if 0
asm void fn_8000DAB0(void) {
#include "src/game/gs_npc_interact_fn_8000DAB0.inc"
}
#else
#pragma peephole off
u32 fn_8000DAB0(void) {
    lbl_8047A2B0 = menuOpen(lbl_8047A2A4, 1);
    GSthreadUnblockGroup(lbl_8047A2A8);
    return lbl_8047A2B0;
}
#pragma peephole on
#endif

/* menuFightDrawTimer - 0x8000DAE8 | size: 0x1a0 */
extern void* fn_8001D834(void*, void*);
extern void fn_800FBB34(void);
extern u16 lbl_802E4B98[];
extern u16 lbl_803A1B80[];
#if 0
asm void menuFightDrawTimer(void) {
#include "src/game/gs_npc_interact_fn_8000DAE8.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawTimer(u8* ctx, u8* npc) {
    extern s32 windowGetParam(u8* a, s32 b);
    extern void msgctrlSetValue(s32 a, s32 b);
    extern void fn_800FB680();
    extern void fn_800FBB34();
    s32 value;
    s32 hour;
    s32 minute;
    s32 digit;
    s16 npcId;

    npcId = *(s16*)(npc + 6);
    if (npcId == 0x12AD) {
        value = windowGetParam(ctx, 0);
        minute = value % 60;
        hour = value / 60;
        lbl_803A1B80[2] = 0x3A;
        lbl_803A1B80[5] = 0;
        digit = hour / 10;
        lbl_803A1B80[0] = lbl_802E4B98[digit];
        digit = hour - (digit * 10);
        lbl_803A1B80[1] = lbl_802E4B98[digit];
        digit = minute / 10;
        lbl_803A1B80[3] = lbl_802E4B98[digit];
        digit = minute - (digit * 10);
        lbl_803A1B80[4] = lbl_802E4B98[digit];
        msgctrlSetValue(0x37, value);
        fn_800FB680(0, 0, (s32)menuSubCalcColor(ctx, npc), 0xCF);
    } else if (npcId == 0x12AF) {
        value = windowGetParam(ctx, 0);
        msgctrlSetValue(0x34, value);
        fn_800FBB34(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56),
                    (s32)menuSubCalcColor(ctx, npc), 0xDE);
    }
}
#pragma pop
#endif

/* menuFightCtrlTimer - 0x8000DC88 | size: 0x84 */
extern void fightTimerAllGetNokoriTime(void);
extern void windowSetParam(void);
extern void fightTimerCommandGetNokoriTime(void);
#if 0
asm void menuFightCtrlTimer(void) {
#include "src/game/gs_npc_interact_fn_8000DC88.inc"
}
#else
#pragma peephole off
u32 menuFightCtrlTimer(u8* ptr) {
    extern f64 fightTimerAllGetNokoriTime(void);
    extern f64 fightTimerCommandGetNokoriTime(void);
    extern void windowSetParam(u8* a, u32 b, s32 c);
    switch (*(s32*)(ptr + 4)) {
        case 0x10a:
            windowSetParam(ptr, 0, (s32)fightTimerAllGetNokoriTime());
            break;
        case 0x10b:
            windowSetParam(ptr, 0, (s32)fightTimerCommandGetNokoriTime());
            break;
    }
    return 0;
}
#pragma peephole on
#endif

/* menuFightCloseCheckTotalTimer - 0x8000DD0C | size: 0x24 */
#if 0
asm void menuFightCloseCheckTotalTimer(void) {
#include "src/game/gs_npc_interact_fn_8000DD0C.inc"
}
#else
#pragma peephole off
u32 menuFightCloseCheckTotalTimer(void) { return menuIsCheck(0x10a); }
#pragma peephole on
#endif

/* menuFightCloseTotalTimer - 0x8000DD30 | size: 0x2c */
#if 0
asm void menuFightCloseTotalTimer(void) {
#include "src/game/gs_npc_interact_fn_8000DD30.inc"
}
#else
#pragma peephole off
void menuFightCloseTotalTimer(void) { menuCloseCustom(0x10a, 0, 0); }
#pragma peephole on
#endif

/* menuFightOpenTotalTimer - 0x8000DD5C | size: 0x3c */
#if 0
asm void menuFightOpenTotalTimer(void) {
#include "src/game/gs_npc_interact_fn_8000DD5C.inc"
}
#else
#pragma peephole off
void menuFightOpenTotalTimer(void) { menuOpenCustom(0x10a, -1, 0, 0, 0, 0); }
#pragma peephole on
#endif

/* menuFightCloseCheckCountDown - 0x8000DD98 | size: 0x24 */
#if 0
asm void menuFightCloseCheckCountDown(void) {
#include "src/game/gs_npc_interact_fn_8000DD98.inc"
}
#else
#pragma peephole off
u32 menuFightCloseCheckCountDown(void) { return menuIsCheck(0x10b); }
#pragma peephole on
#endif

/* menuFightCloseCountDown - 0x8000DDBC | size: 0x2c */
#if 0
asm void menuFightCloseCountDown(void) {
#include "src/game/gs_npc_interact_fn_8000DDBC.inc"
}
#else
#pragma peephole off
void menuFightCloseCountDown(void) { menuCloseCustom(0x10b, 0, 0); }
#pragma peephole on
#endif

/* menuFightOpenCountDown - 0x8000DDE8 | size: 0x3c */
#if 0
asm void menuFightOpenCountDown(void) {
#include "src/game/gs_npc_interact_fn_8000DDE8.inc"
}
#else
#pragma peephole off
void menuFightOpenCountDown(void) { menuOpenCustom(0x10b, -1, 0, 0, 0, 0); }
#pragma peephole on
#endif

/* menuFightButtonSecretKousan - 0x8000DE24 | size: 0xa0 */
extern void menuButtonNormal(void);
#if 0
asm void menuFightButtonSecretKousan(void) {
#include "src/game/gs_npc_interact_fn_8000DE24.inc"
}
#else
#pragma push
#pragma peephole off
#pragma peephole off
#pragma peephole off
#pragma peephole off
void menuFightButtonSecretKousan(u8* ptr) {
    extern void menuButtonNormal(u8* a);
    extern u8 fn_801F18DC(s32 a);
    extern u8 fightFloorIsUseFightTimerCommand(s32 a);
    extern u8 fightTimerCommandIsOver(void);
    extern u16 fn_801EF634(void);
    u8 flag;
    menuButtonNormal(ptr);
    if (!(u8)fn_801F18DC(0)) goto _zero;
    if ((u8)fightFloorIsUseFightTimerCommand(0) == 1 && (u8)fightTimerCommandIsOver() == 1) { flag = 1; goto _check; }
    if ((u16)fn_801EF634() == 1) { flag = 1; goto _check; }
    _zero:
    flag = 0;
    _check:
    if (flag) {
        ptr[0x98] = 1;
        ptr[0x99] = 1;
    }
}
#pragma peephole on
#pragma peephole on
#pragma peephole on
#pragma pop
#endif

/* menuFightDrawTargetSecret - 0x8000DEC4 | size: 0x12c */
#if 0
asm void menuFightDrawTargetSecret(void) {
#include "src/game/gs_npc_interact_fn_8000DEC4.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawTargetSecret(u8* arg1, u8* arg2) {
    extern void* windowGetParam(u8* a, u32 b);
    extern void winSpriteSetDisp(u8* a, u32 b);
    u8* entry;
    s32 i;
    entry = (u8*)windowGetParam(arg1, 0);
    for (i = 0; i < 2; i++) {
        s32 value;
        s16 npc_id;
        switch (*(s32*)(entry + 4)) {
            case 0x45: value = 0x125C; break;
            case 0x46: value = 0x125E; break;
            case 0x47: value = 0x12BE; break;
            case 0x48: value = 0x125D; break;
            default: value = 0; break;
        }
        npc_id = *(s16*)(arg2 + 6);
        if (value == npc_id) {
            winSpriteSetDisp(arg2, 1);
            return;
        }
        switch (*(s32*)(entry + 0xC)) {
            case 0x45: value = 0x125C; break;
            case 0x46: value = 0x125E; break;
            case 0x47: value = 0x12BE; break;
            case 0x48: value = 0x125D; break;
            default: value = 0; break;
        }
        if (value == npc_id) {
            winSpriteSetDisp(arg2, 1);
            return;
        }
        entry += 0x10;
    }
    winSpriteSetDisp(arg2, 0);
}
#pragma pop
#endif

/* menuFightButtonTargetSecret - 0x8000DFF0 | size: 0x214 */
extern u8* windowGetKeyInfo();
#if 0
asm void menuFightButtonTargetSecret(void) {
#include "src/game/gs_npc_interact_fn_8000DFF0.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightButtonTargetSecret(u8* ctx) {
    extern u8* windowGetKeyInfo(void);
    extern u32 windowGetParam(u8* a, s32 b);
    u8* flags;
    u8* entry;
    u16 bits;
    s32 selected;
    s32 i;
    s32 mode;
    s32 field;
    u8 pressed;

    flags = windowGetKeyInfo();
    entry = (u8*)windowGetParam(ctx, 0);
    selected = -1;
    bits = *(u16*)(flags + 4);
    if (bits & 1) {
        selected = 0;
    } else if (bits & 8) {
        selected = 1;
    } else if (bits & 4) {
        selected = 2;
    } else if (bits & 0x400) {
        ctx[0x98] = 1;
        ctx[0x99] = 1;
        *(s32*)(ctx + 0x80) = -1;
    }

    if (selected >= 0) {
        for (i = 0; i < 2; i++, entry += 0x10) {
            field = *(s32*)(entry + 4);
            if (field == 0x45) {
                mode = 1;
            } else if (field == 0x46) {
                mode = 0;
            } else if (field == 0x47 || field == 0x48) {
                mode = 2;
            } else {
                mode = -1;
            }
            if (selected == mode) {
                ctx[0x98] = 1;
                *(s32*)(ctx + 0x80) = selected;
                return;
            }
            field = *(s32*)(entry + 0xC);
            if (field == 0x45) {
                mode = 1;
            } else if (field == 0x46) {
                mode = 0;
            } else if (field == 0x47 || field == 0x48) {
                mode = 2;
            } else {
                mode = -1;
            }
            if (selected == mode) {
                ctx[0x98] = 1;
                *(s32*)(ctx + 0x80) = selected;
                return;
            }
        }
    }

    pressed = 0;
    if ((u8)fn_801F18DC(0) != 0) {
        if (((u8)fightFloorIsUseFightTimerCommand(0) == 1) && ((u8)fightTimerCommandIsOver() == 1)) {
            pressed = 1;
        } else if ((u16)fn_801EF634() == 1) {
            pressed = 1;
        }
    }
    if (pressed != 0) {
        ctx[0x98] = 1;
        ctx[0x99] = 1;
    }
}
#pragma pop
#endif

/* menuFightDrawTargetCursor - 0x8000E204 | size: 0x88 */
extern void menuItemBiosGetSelectFlag(void);
extern void menuGetCursorItemID(void);
#if 0
asm void menuFightDrawTargetCursor(void) {
#include "src/game/gs_npc_interact_fn_8000E204.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawTargetCursor(u8* arg1, u8* arg2) {
    extern u32 menuItemBiosGetSelectFlag(s16 val);
    extern s32 menuGetCursorItemID(u32 val);
    extern void winSpriteSetDisp(u8* a, u32 b);
    if ((u8)menuItemBiosGetSelectFlag(*(s16*)(arg2 + 6)) != 0) {
        if (*(s16*)(arg2 + 6) == menuGetCursorItemID(*(u32*)(arg1 + 4))) {
            winSpriteSetDisp(arg2, 1);
        } else {
            winSpriteSetDisp(arg2, 0);
        }
    } else {
        winSpriteSetDisp(arg2, 0);
    }
}
#pragma pop
#endif

/* menuFightCtrlTarget - 0x8000E28C | size: 0x4 */
#if 0
asm void menuFightCtrlTarget(void) {
#include "src/game/gs_npc_interact_fn_8000E28C.inc"
}
#else
void menuFightCtrlTarget(void) {}
#endif

/* menuFightDrawSecretPokemonStatus - 0x8000E290 | size: 0x780 */
extern void* pokemonDataBiosGetPtr();
extern u8 pokemonDataBiosGetZokuseiDataId();
extern u16 fn_8010C46C();
extern u32 wazaGetStatus();
extern u8 pokemonWazaGetMaxPP();
extern u32 GSmsgGetGSchar();
extern u16 pokemonGetSoubiItemDataId();
extern void* itemDataBiosGetPtr();
extern u32 itemDataBiosGetName();
extern u32 pokemonDataBiosGetName();
extern u8 menuSubGetPokemonSexForDisp();

/* Draw one field in the six-party secret-Pokemon status panel. */
#pragma push
#pragma peephole off
void menuFightDrawSecretPokemonStatus(u8* ctx, u8* sprite)
{
    extern u32 windowGetParam();
    extern u32 fightFloorGetGcHeroFightTrainerPtr();
    extern u32 fightTrainerGetValidFightPokemonPtr();
    extern u32 pokemonGetStatus();
    extern u32 pokemonCheckValid();
    extern u32 fn_8001D624();
    extern u32 pokemonDataBiosGetPtr();
    extern u32 pokemonDataBiosGetZokuseiDataId();
    extern u32 fn_8010C46C();
    extern u32 wazaGetStatus();
    extern u32 pokemonWazaGetMaxPP();
    extern u32 pokemonGetSoubiItemDataId();
    extern u32 itemDataBiosGetPtr();
    extern u32 itemDataBiosGetName();
    extern u32 pokemonDataBiosGetName();
    extern u32 GSmsgGetGSchar();
    extern u32 menuSubGetPokemonSexForDisp();
    extern void fn_800FBB34();
    u32 trainer;
    u32 resolvedTrainer;
    s32* selection;
    u32 pokemon;
    s32 color;
    s32 id;
    s32 slot;

    slot = -1;
    trainer = windowGetParam(ctx, 0);
    resolvedTrainer = trainer;
    selection = (s32*)windowGetParam(ctx, 1);
    if (*selection < 0) {
        return;
    }

    pokemon = (u16)*selection;
    if (pokemon >= 6) {
        pokemon = 0;
    } else {
        if (resolvedTrainer == 0) {
            resolvedTrainer = fightFloorGetGcHeroFightTrainerPtr(0);
        }
        if (resolvedTrainer == 0) {
            pokemon = 0;
        } else {
            pokemon = fightTrainerGetValidFightPokemonPtr(resolvedTrainer, (u16)pokemon);
            if (pokemon == 0) {
                pokemon = 0;
            } else {
                pokemon = pokemonGetStatus(pokemon, 0, 0xCC, 0);
                if ((u8)pokemonCheckValid(pokemon) == 0) {
                    pokemon = 0;
                }
            }
        }
    }
    if (pokemon == 0) {
        return;
    }

    color = (s32)menuSubCalcColor(ctx, sprite);
    id = *(s16*)(sprite + 6);
    switch (id) {
    case 0x1235:
    case 0x1236:
    case 0x1237:
    case 0x1238:
    case 0x1239:
    case 0x123A:
        switch (id) {
        case 0x1238: slot = 0; break;
        case 0x1235: slot = 1; break;
        case 0x1236: slot = 3; break;
        case 0x1237: slot = 2; break;
        case 0x123A: slot = 4; break;
        case 0x1239: slot = 5; break;
        default: break;
        }
        if (slot == *selection) {
            winSpriteSetDisp(sprite, 1);
        } else {
            winSpriteSetDisp(sprite, 0);
        }
        break;

    case 0x123B:
        windowDrawSprite(0, 0, ctx, fn_8001D624(pokemon, 1), 0);
        break;

    case 0x123D: {
        u32 data = pokemonDataBiosGetPtr((u16)pokemonGetStatus(pokemon, 0, 0x6E, 0));
        u8 type = pokemonDataBiosGetZokuseiDataId(data, 0);
        windowDrawSprite(0, 0, ctx, (u16)fn_8010C46C(type), 0);
        break;
    }

    case 0x123C: {
        u8 first;
        u8 second;
        u32 data = pokemonDataBiosGetPtr((u16)pokemonGetStatus(pokemon, 0, 0x6E, 0));
        first = pokemonDataBiosGetZokuseiDataId(data, 0);
        second = pokemonDataBiosGetZokuseiDataId(data, 1);
        if (first != second) {
            windowDrawSprite(0, 0, ctx, (u16)fn_8010C46C(second), 0);
        }
        break;
    }

    case 0x123E:
    case 0x123F:
    case 0x1240:
    case 0x1241: {
        u16 move;
        switch (id) {
        case 0x123E: slot = 3; break;
        case 0x123F: slot = 2; break;
        case 0x1240: slot = 1; break;
        case 0x1241: slot = 0; break;
        }
        move = (u16)pokemonGetStatus(pokemon, 0, 0x7F, (u16)slot);
        if (move != 0) {
            u16 icon = (u16)wazaGetStatus(0, move, 3, 0);
            windowDrawSprite(0, 0, ctx, (u16)fn_8010C46C(icon), 0);
        }
        break;
    }

    case 0x1242:
    case 0x1243:
    case 0x1244:
    case 0x1245: {
        s32 x;
        u32 sign;
        u16 move;
        switch (id) {
        case 0x1242: slot = 3; break;
        case 0x1243: slot = 2; break;
        case 0x1244: slot = 1; break;
        case 0x1245: slot = 0; break;
        }
        move = (u16)pokemonGetStatus(pokemon, 0, 0x7F, (u16)slot);
        if (move == 0) {
            break;
        }
        x = (*(s16*)(sprite + 0x54) - (s16)(GSmsgGetRect(0x197) >> 16));
        sign = (u32)x >> 31;
        x = (s32)(sign + x) >> 1;
        fn_800FB680((s16)x, 0, color, 0x197);
        msgctrlSetValue(0x34, pokemonGetStatus(pokemon, 0, 0x80, (u16)slot));
        fn_800FBB34(0, 0, (s16)x, *(s16*)(sprite + 0x56), color, 0xDE);
        msgctrlSetValue(0x34, (u8)pokemonWazaGetMaxPP(pokemon, (u16)slot));
        fn_800FBB34(0, 0, *(s16*)(sprite + 0x54), *(s16*)(sprite + 0x56),
                    color, 0xDE);
        break;
    }

    case 0x1246:
    case 0x1247:
    case 0x1248:
    case 0x1249: {
        u16 move;
        u32 name;
        switch (id) {
        case 0x1246: slot = 3; break;
        case 0x1247: slot = 2; break;
        case 0x1248: slot = 1; break;
        case 0x1249: slot = 0; break;
        }
        move = (u16)pokemonGetStatus(pokemon, 0, 0x7F, (u16)slot);
        if (move == 0) {
            break;
        }
        name = wazaGetStatus(0, move, 1, 0);
        if (name == 0) {
            break;
        }
        msgctrlSetValue(0x37, GSmsgGetGSchar(name));
        fn_800FBB34(0, 0, *(s16*)(sprite + 0x54), *(s16*)(sprite + 0x56),
                    color, 0xE7);
        break;
    }

    case 0x124A: {
        u16 item = (u16)pokemonGetSoubiItemDataId(pokemon);
        if (item != 0) {
            u32 data = itemDataBiosGetPtr(item);
            msgctrlSetValue(0x37, GSmsgGetGSchar(itemDataBiosGetName(data)));
            fn_800FBB34(0, 0, *(s16*)(sprite + 0x54), *(s16*)(sprite + 0x56),
                        color, 0xE7);
        }
        break;
    }

    case 0x124B: {
        s32 firstWidth = (s16)(GSmsgGetRect(0x1A8) >> 16) + 2;
        s32 delta;
        s32 x;
        s32 half;
        fn_800FB680(0, 0, color, 0x1A8);
        delta = *(s16*)(sprite + 0x54) - firstWidth -
                (s16)(GSmsgGetRect(0x197) >> 16);
        half = (s32)(((u32)delta >> 31) + delta) >> 1;
        x = firstWidth + (s16)half;
        fn_800FB680((s16)x, 0, color, 0x197);
        msgctrlSetValue(0x34, (s16)pokemonGetStatus(pokemon, 0, 0x83, 0));
        fn_800FBB34(0, 0, (s16)x, *(s16*)(sprite + 0x56), color, 0xDE);
        msgctrlSetValue(0x34, (s16)pokemonGetStatus(pokemon, 0, 0x87, 0));
        fn_800FBB34(0, 0, *(s16*)(sprite + 0x54), *(s16*)(sprite + 0x56),
                    color, 0xDE);
        break;
    }

    case 0x124C: {
        s16 width = (s16)(GSmsgGetRect(0x1A7) >> 16);
        fn_800FB680(0, 0, color, 0x1A7);
        msgctrlSetValue(0x34, (u8)pokemonGetStatus(pokemon, 0, 0x7A, 0));
        fn_800FBB34(width, 0, *(s16*)(sprite + 0x54), *(s16*)(sprite + 0x56),
                    color, 0xD2);
        break;
    }

    case 0x124D: {
        s16 width = 0;
        u32 data = pokemonDataBiosGetPtr((u16)pokemonGetStatus(pokemon, 0, 0x6E, 0));
        if (data != 0) {
            u32 name = pokemonDataBiosGetName(data);
            if (name != 0) {
                msgctrlSetValue(0x37, GSmsgGetGSchar(name));
                fn_800FB680(0, 0, color, 0xE7);
                width = (s16)(GSmsgGetRect(0xE7) >> 16);
            }
            switch ((u8)menuSubGetPokemonSexForDisp(pokemon)) {
            case 0: name = 0xD67; break;
            case 1: name = 0xD68; break;
            default: name = 0; break;
            }
            if (name != 0) {
                msgctrlSetValue(0x37, GSmsgGetGSchar(name));
                fn_800FB680(width, 0, color, 0xCF);
            }
        }
        break;
    }

    case 0x124E: {
        u32 value = pokemonGetStatus(pokemon, 0, 0x77, 0);
        msgctrlSetValue(0x37, value);
        fn_800FBB34(0, 0, *(s16*)(sprite + 0x54), *(s16*)(sprite + 0x56),
                    color, 0xE7);
        break;
    }
    }
}
#pragma pop

/* menuFightDrawSecretPokemon - 0x8000EA10 | size: 0x324 */
extern u32 fightFloorGetGcHeroFightTrainerPtr(s32 arg);
extern u32 fightTrainerGetValidFightPokemonPtr(u32 warpId, u16 variant);
extern u32 pokemonGetStatus();
extern u32 pokemonCheckValid();
extern u32 fn_8001D624();
extern void jumptable_802E4C20();
#if 0
asm void menuFightDrawSecretPokemon(void) {
#include "src/game/gs_npc_interact_fn_8000EA10.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawSecretPokemon(u8* ctx, u8* npc) {
    extern u32 windowGetParam(u8* a, s32 b);
    extern u32 pokemonGetStatus();
    extern u32 pokemonCheckValid(void);
    extern u32 fn_8001D624(u32, s32);
    extern void fn_800FBB34();
    extern void fn_800FB680();
    s32 idx;
    s32 slot;
    u32 handle;
    s32 color;
    s32 npcId;
    s32 y;
    s32 top;
    s32 delta;

    handle = windowGetParam(ctx, 0);
    npcId = *(s16*)(npc + 6);
    idx = npcId - 0x1215;
    slot = -1;
    if ((u32)idx <= 0x17) {
        slot = idx % 6;
    }
    if (slot < 0) return;
    if ((u32)slot >= 6) return;
    if (handle == 0) {
        handle = fightFloorGetGcHeroFightTrainerPtr(0);
    }
    if (handle == 0) return;
    handle = fightTrainerGetValidFightPokemonPtr(handle, (u16)slot);
    if (handle == 0) return;
    handle = pokemonGetStatus(handle, 0, 0xCC, 0);
    if ((u8)pokemonCheckValid() == 0) return;

    color = (s32)menuSubCalcColor(ctx, npc);
    if (npcId >= 0x1215 && npcId < 0x121B) {
        windowDrawSprite(0, 0, ctx, (u16)fn_8001D624(handle, 1), 0);
    } else if (npcId >= 0x121B && npcId < 0x1221) {
        y = (s16)(GSmsgGetRect(0x1A8) >> 16) + 2;
        fn_800FB680(0, 0, color, 0x1A8);
        top = (s16)(GSmsgGetRect(0x197) >> 16);
        delta = *(s16*)(npc + 0x54) - y - top;
        y = y + ((delta + ((u32)delta >> 31)) >> 1);
        fn_800FB680(y, 0, color, 0x197);
        msgctrlSetValue(0x34, (s16)pokemonGetStatus(handle, 0, 0x83, 0));
        fn_800FBB34(0, 0, (s16)y, *(s16*)(npc + 0x56), color, 0xDE);
        msgctrlSetValue(0x34, (s16)pokemonGetStatus(handle, 0, 0x87, 0));
        fn_800FBB34(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0xDE);
    } else if (npcId >= 0x1221 && npcId < 0x1227) {
        y = (s16)(GSmsgGetRect(0x1A7) >> 16);
        fn_800FB680(0, 0, color, 0x1A7);
        msgctrlSetValue(0x34, (u8)pokemonGetStatus(handle, 0, 0x7A, 0));
        fn_800FBB34(y, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0xD2);
    } else if (npcId >= 0x1227 && npcId < 0x122D) {
        msgctrlSetValue(0x37, pokemonGetStatus(handle, 0, 0x77, 0));
        fn_800FBB34(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0xE7);
    }
}
#pragma pop
#endif

/* menuFightButtonSecretPokemonTop - 0x8000ED34 | size: 0x5dc */
extern void menuSetDisp(void);
extern void fn_800F7920(void);
extern void fn_800F7994(void);
extern void atan2(void);
extern u32 lbl_8047B710;
extern u32 lbl_8047B700;
extern u32 lbl_8047B704;
extern u32 lbl_8047B708;
extern u8 lbl_8047885C[4];
#if 0
asm void menuFightButtonSecretPokemonTop(void) {
#include "src/game/gs_npc_interact_fn_8000ED34.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightButtonSecretPokemonTop(u8* ctx) {
    extern u8* windowGetKeyInfo(void);
    extern u32 windowGetParam(u8* a, s32 b);
    extern void menuSetDisp(u32, s32);
    extern u8 menuIsCheck(s32);
    extern s8 fn_800F7920(s32, s32);
    extern s8 fn_800F7994(s32, s32);
    extern u32 pokemonGetStatus();
    extern u32 pokemonCheckValid(void);
    extern s32 menuOpenCustom(s32, ...);
    u8* flags;
    u32 base;
    u32 aux;
    s32 activeMenu;
    s32 targetMenu;
    s32 selected;
    s32 x;
    s32 y;
    s32 absX;
    s32 absY;
    u16 bits;
    u8 pressed;
    u32 handle;
    s32 stored;

    flags = windowGetKeyInfo();
    base = windowGetParam(ctx, 0);
    windowGetParam(ctx, 1);
    aux = windowGetParam(ctx, 2);
    menuSetDisp(*(u32*)(ctx + 4), 1);
    activeMenu = 0;
    targetMenu = 0;
    selected = -1;
    if ((u8)menuIsCheck(0xFC) != 0) {
        activeMenu = 0xFC;
    } else if ((u8)menuIsCheck(0xFD) != 0) {
        activeMenu = 0xFD;
    }

    x = (s8)fn_800F7920(1, 0);
    y = (s8)fn_800F7994(1, 0);
    absX = (x < 0) ? -x : x;
    absY = (y < 0) ? -y : y;
    if (absX > 0x20 || absY > 0x20) {
        if (absX < absY) {
            selected = (y < 0) ? 2 : 3;
        } else {
            selected = (x < 0) ? 0 : 1;
        }
    }
    if (selected < 0) {
        bits = *(u16*)(flags + 4);
        if (bits & 0x80) {
            selected = 4;
        } else if (bits & 0x40) {
            selected = 5;
        }
    }

    if (selected >= 0) {
        handle = base;
        if ((u32)(u16)selected < 6) {
            if (handle == 0) {
                handle = fightFloorGetGcHeroFightTrainerPtr(0);
            }
            if (handle != 0) {
                handle = fightTrainerGetValidFightPokemonPtr(handle, (u16)selected);
                if (handle != 0) {
                    handle = pokemonGetStatus(handle, 0, 0xCC, 0);
                    if ((u8)pokemonCheckValid() == 0) {
                        handle = 0;
                    }
                }
            }
        } else {
            handle = 0;
        }
        if (handle != 0) {
            ctx[0x98] = 1;
            *(s32*)(ctx + 0x80) = selected;
        } else {
            selected = -1;
        }
    }

    if (selected < 0) {
        bits = *(u16*)(flags + 4);
        if ((bits & 0x400) && ((u8)aux != 0)) {
            ctx[0x98] = 1;
            ctx[0x99] = 1;
            *(s32*)(ctx + 0x80) = -1;
        } else if (*(u16*)flags & 0x800) {
            menuSetDisp(*(u32*)(ctx + 4), 0);
            stored = -1;
            if (*(u16*)flags & 1) {
                if (*(u16*)flags & 8) {
                    stored = 5;
                } else if (*(u16*)flags & 4) {
                    stored = 4;
                } else {
                    stored = 0;
                }
            } else if (*(u16*)flags & 2) {
                stored = 2;
            } else if (*(u16*)flags & 8) {
                stored = 1;
            } else if (*(u16*)flags & 4) {
                stored = 3;
            }
            *(s32*)lbl_8047885C = stored;
            if (stored < 0) {
                targetMenu = 0xFC;
            } else {
                targetMenu = 0xFD;
            }
        }
    }

    pressed = 0;
    if ((u8)fn_801F18DC(0) != 0) {
        if (((u8)fightFloorIsUseFightTimerCommand(0) == 1) && ((u8)fightTimerCommandIsOver() == 1)) {
            pressed = 1;
        } else if ((u16)fn_801EF634() == 1) {
            pressed = 1;
        }
    }
    if (pressed != 0) {
        ctx[0x98] = 1;
        ctx[0x99] = 1;
    }

    if (activeMenu != targetMenu) {
        if (activeMenu != 0) {
            menuClose(activeMenu);
        }
        if (ctx[0x98] == 0) {
            if (targetMenu == 0xFC) {
                menuOpenCustom(0xFC, *(u32*)(ctx + 4), 0, 0, 0, 1, base);
                menuSetDisp(0xFC, 1);
                menuSetDisp(0xFD, 0);
            } else if (targetMenu == 0xFD) {
                menuOpenCustom(0xFD, *(u32*)(ctx + 4), 0, 0, 0, 2, base, lbl_8047885C);
                menuSetDisp(0xFD, 1);
                menuSetDisp(0xFC, 0);
            }
        }
    }
}
#pragma pop
#endif

/* menuFightCtrlSecretPokemonTop - 0x8000F310 | size: 0x4c */
#if 0
asm void menuFightCtrlSecretPokemonTop(void) {
#include "src/game/gs_npc_interact_fn_8000F310.inc"
}
#else
#pragma peephole off
u32 menuFightCtrlSecretPokemonTop(u32 arg) {
    windowGetParam((void*)arg, 0);
    windowGetParam((void*)arg, 1);
    windowGetParam((void*)arg, 2);
    return 0;
}
#pragma peephole on
#endif

/* menuFightDrawSecretSelect - 0x8000F35C | size: 0xa4 */
extern void jumptable_802E4C80();
#if 0
asm void menuFightDrawSecretSelect(void) {
#include "src/game/gs_npc_interact_fn_8000F35C.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawSecretSelect(u8* ctx, u8* npc) {
    s32 visible;
    s32 id;
    s32 idx;
    s32 state;

    visible = 1;
    state = *(s32*)(ctx + 4);
    if (state == 0xF7) {
        goto visibility_done;
    }
    if (state == 0xF8) {
        if ((u8)windowGetParam(ctx, 2) == 0) {
            visible = 0;
        }
    }
visibility_done:
    id = *(s16*)(npc + 6);
    idx = id - 0x11CE;
    switch (idx) {
    case 1:
    case 5:
    case 8:
        winSpriteSetDisp(npc, 1);
        break;
    case 0:
    case 6:
    case 9:
        winSpriteSetDisp(npc, visible);
        break;
    default:
        break;
    }
}
#pragma pop
#endif

/* menuFightDrawSecretWazaDoc - 0x8000F400 | size: 0x368 */
extern u32 fightOutPokemonGetPokemonPtr();
extern void fn_800FB8C8(void);
extern void jumptable_802E4CA8();
#if 0
asm void menuFightDrawSecretWazaDoc(void) {
#include "src/game/gs_npc_interact_fn_8000F400.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawSecretWazaDoc(u8* ctx, u8* npc) {
    extern u32 windowSearchID(void);
    extern u8* windowGetAllocPtr(void);
    extern u32 windowGetParam(u8* a, s32 b);
    extern u32 fightOutPokemonGetPokemonPtr(void*);
    extern u32 pokemonGetStatus();
    extern u32 pokemonCheckValid(void);
    extern u32 wazaGetStatus();
    extern void fn_800FBB34();
    extern void fn_800FB8C8();
    extern void fn_800FB680();
    u8* party;
    u8* state;
    u32 battle;
    u32 result;
    s32 id;
    s32 color;
    s32 value;
    s32 y0;
    s32 y1;
    s32 delta;

    value = -1;
    windowGetParam(ctx, 0);
    if (windowSearchID() == 0) return;
    party = windowGetAllocPtr();
    if (party == NULL) return;
    state = (u8*)windowGetParam(ctx, 1);
    if (*(s32*)state < 0) return;
    battle = fightOutPokemonGetPokemonPtr(*(void**)(party + 0x40));
    if (battle == 0) return;
    result = pokemonGetStatus(battle, 0, 0x7F, (u16)*(s32*)state);
    color = (s32)menuSubCalcColor(ctx, npc);
    id = *(s16*)(npc + 6);

    switch (id) {
    case 0x11F4:
    case 0x11F5:
    case 0x11F6:
    case 0x11F7:
        if (id == 0x11F4) value = 1;
        else if (id == 0x11F5) value = 3;
        else if (id == 0x11F6) value = 2;
        else value = 0;
        if (value == *(s32*)state) {
            winSpriteSetDisp(npc, 1);
        } else {
            winSpriteSetDisp(npc, 0);
        }
        break;
    case 0x11F8:
        windowDrawSprite(0, 0, ctx,
                         *(u16*)(party + (*(s32*)state * 0xC) + 0xC), 0);
        break;
    case 0x11F9:
        value = wazaGetStatus(0, (u16)result, 0x22, 0);
        fn_800FBB34(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, value);
        break;
    case 0x11FA:
        value = wazaGetStatus(0, (u16)result, 6, 0);
        if ((u32)value <= 1) {
            fn_800FB8C8(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0x2BE2);
        } else {
            msgctrlSetValue(0x34, value);
            fn_800FB8C8(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0xD2);
        }
        break;
    case 0x11FC:
        value = wazaGetStatus(0, (u16)result, 7, 0);
        if ((u32)value <= 1) {
            fn_800FB8C8(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0x2BE2);
        } else {
            msgctrlSetValue(0x34, value);
            fn_800FB8C8(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0xD2);
        }
        break;
    case 0x11FE:
        msgctrlSetValue(0x37,
                        *(u32*)(party + (*(s32*)state * 0xC) + 4));
        fn_800FB680(0, 0, color, 0xCF);
        break;
    case 0x11FF:
        y0 = (s16)(GSmsgGetRect(0x1A4) >> 16);
        delta = *(s16*)(npc + 0x54) - y0;
        fn_800FB680(0, 0, color, 0x1A4);
        y1 = (s16)(GSmsgGetRect(0x197) >> 16);
        y1 = (s16)((s32)(delta - y1 + ((u32)(delta - y1) >> 31)) >> 1);
        fn_800FB680(y0 + y1, 0, color, 0x197);
        msgctrlSetValue(0x34,
                        *(u8*)(party + (*(s32*)state * 0xC) + 0xF));
        fn_800FBB34(y0, 0, y1, *(s16*)(npc + 0x56), color, 0xDE);
        msgctrlSetValue(0x34,
                        *(u8*)(party + (*(s32*)state * 0xC) + 0xE));
        fn_800FBB34(y0, 0, delta, *(s16*)(npc + 0x56), color, 0xDE);
        break;
    default:
        break;
    }
}
#pragma pop
#endif

/* menuFightDrawSecretWazaSelect - 0x8000F768 | size: 0x1fc */
extern void jumptable_802E4CD8();
#if 0
asm void menuFightDrawSecretWazaSelect(void) {
#include "src/game/gs_npc_interact_fn_8000F768.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawSecretWazaSelect(u8* ctx, u8* npc) {
    extern u32 windowSearchID(void);
    extern u8* windowGetAllocPtr(void);
    extern u32 windowGetParam(u8* a, s32 b);
    extern void fn_800FBB34();
    extern void fn_800FB680();
    u8* entries;
    u8* entry;
    s32 slot;
    s32 idx;
    s32 color;
    s32 y;
    s32 delta;

    slot = -1;
    windowGetParam(ctx, 0);
    if (windowSearchID() == 0) return;
    entries = windowGetAllocPtr();
    if (entries == NULL) return;
    color = (s32)menuSubCalcColor(ctx, npc);
    idx = *(s16*)(npc + 6) - 0x11D9;
    switch (idx) {
    case 3:
    case 7:
    case 11:
    case 15:
    case 19:
        slot = 0;
        break;
    case 0:
    case 4:
    case 8:
    case 12:
    case 16:
    case 20:
        slot = 1;
        break;
    case 1:
    case 5:
    case 9:
    case 13:
    case 17:
        slot = 2;
        break;
    case 2:
    case 6:
    case 10:
    case 14:
    case 18:
        slot = 3;
        break;
    default:
        break;
    }
    if (slot < 0) return;
    entry = entries + (slot * 0xC);
    if (*(u32*)(entry + 4) != 0) {
        winSpriteSetDisp(npc, 1);
    } else {
        winSpriteSetDisp(npc, 0);
        return;
    }

    switch (*(s16*)(npc + 6)) {
    case 0x11E2:
    case 0x11E3:
    case 0x11E4:
    case 0x11E5:
        windowDrawSprite(0, 0, ctx, *(u16*)(entry + 0xC), 0);
        break;
    case 0x11E6:
    case 0x11E7:
    case 0x11E8:
    case 0x11E9:
        y = (s16)(GSmsgGetRect(0x197) >> 16);
        delta = *(s16*)(npc + 0x54) - y;
        y = (s16)((delta + ((u32)delta >> 31)) >> 1);
        fn_800FB680(y, 0, color, 0x197);
        msgctrlSetValue(0x34, *(u8*)(entry + 0xF));
        fn_800FBB34(0, 0, y, *(s16*)(npc + 0x56), color, 0xDE);
        msgctrlSetValue(0x34, *(u8*)(entry + 0xE));
        fn_800FBB34(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0xDE);
        break;
    case 0x11EA:
    case 0x11EB:
    case 0x11EC:
    case 0x11ED:
        msgctrlSetValue(0x37, *(u32*)(entry + 4));
        fn_800FB680(0, 0, color, 0xE7);
        break;
    default:
        break;
    }
}
#pragma pop
#endif

/* menuFightButtonSecretWazaTop - 0x8000F964 | size: 0x474 */
extern u32 lbl_8047B710;
extern u32 lbl_8047B700;
extern u32 lbl_8047B704;
extern u32 lbl_8047B708;
extern u8 lbl_80478858[4];
#if 0
asm void menuFightButtonSecretWazaTop(void) {
#include "src/game/gs_npc_interact_fn_8000F964.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightButtonSecretWazaTop(u8* ctx) {
    extern u8* windowGetKeyInfo(void);
    extern u8* windowGetAllocPtr(u8* a);
    extern void menuSetDisp(u32, s32);
    extern u8 menuIsCheck(s32);
    extern s8 fn_800F7920(s32, s32);
    extern s8 fn_800F7994(s32, s32);
    extern s32 menuOpenCustom(s32, ...);
    u8* flags;
    u8* entries;
    s32 activeMenu;
    s32 targetMenu;
    s32 selected;
    s32 x;
    s32 y;
    s32 absX;
    s32 absY;
    s32 stored;
    u8 pressed;

    flags = windowGetKeyInfo();
    entries = windowGetAllocPtr(ctx);
    selected = -1;
    activeMenu = 0;
    targetMenu = 0;
    menuSetDisp(*(u32*)(ctx + 4), 1);
    if ((u8)menuIsCheck(0xF9) != 0) {
        activeMenu = 0xF9;
    } else if ((u8)menuIsCheck(0xFA) != 0) {
        activeMenu = 0xFA;
    }

    x = (s8)fn_800F7920(1, 0);
    y = (s8)fn_800F7994(1, 0);
    absX = (x < 0) ? -x : x;
    absY = (y < 0) ? -y : y;
    if (absX > 0x20 || absY > 0x20) {
        if (absX < absY) {
            selected = (y < 0) ? 2 : 3;
        } else {
            selected = (x < 0) ? 0 : 1;
        }
    }
    if (selected >= 0 && *(u32*)(entries + (selected * 0xC) + 4) == 0) {
        selected = -1;
    }
    if (selected >= 0) {
        ctx[0x98] = 1;
        *(s32*)(ctx + 0x80) = selected;
    } else if (*(u16*)(flags + 4) & 0x400) {
        ctx[0x98] = 1;
        ctx[0x99] = 1;
        *(s32*)(ctx + 0x80) = -1;
    } else if (*(u16*)flags & 0x800) {
        menuSetDisp(*(u32*)(ctx + 4), 0);
        if (*(u16*)flags & 1) {
            stored = 0;
        } else if (*(u16*)flags & 8) {
            stored = 1;
        } else if (*(u16*)flags & 2) {
            stored = 2;
        } else if (*(u16*)flags & 4) {
            stored = 3;
        } else {
            stored = -1;
        }
        *(s32*)lbl_80478858 = stored;
        if (stored >= 0 && *(u32*)(entries + (stored * 0xC) + 4) == 0) {
            *(s32*)lbl_80478858 = -1;
            stored = -1;
        }
        targetMenu = (stored < 0) ? 0xF9 : 0xFA;
    }

    pressed = 0;
    if ((u8)fn_801F18DC(0) != 0) {
        if (((u8)fightFloorIsUseFightTimerCommand(0) == 1) && ((u8)fightTimerCommandIsOver() == 1)) {
            pressed = 1;
        } else if ((u16)fn_801EF634() == 1) {
            pressed = 1;
        }
    }
    if (pressed != 0) {
        ctx[0x98] = 1;
        ctx[0x99] = 1;
    }

    if (activeMenu != targetMenu) {
        if (activeMenu != 0) {
            menuClose(activeMenu);
        }
        if (ctx[0x98] == 0) {
            if (targetMenu == 0xF9) {
                menuOpenCustom(0xF9, *(u32*)(ctx + 4), 0, 0, 0, 1, *(u32*)(ctx + 4));
                menuSetDisp(0xF9, 1);
                menuSetDisp(0xFA, 0);
            } else if (targetMenu == 0xFA) {
                menuOpenCustom(0xFA, *(u32*)(ctx + 4), 0, 0, 0, 2, *(u32*)(ctx + 4), lbl_80478858);
                menuSetDisp(0xFA, 1);
                menuSetDisp(0xF9, 0);
            }
        }
    }
}
#pragma pop
#endif

/* menuFightCtrlSecretWazaTop - 0x8000FDD8 | size: 0x60 */
extern void windowAllocMemory(void);
extern void* memcpy(void* dst, const void* src, u32 n);
#if 0
asm void menuFightCtrlSecretWazaTop(void) {
#include "src/game/gs_npc_interact_fn_8000FDD8.inc"
}
#else
#pragma peephole off
u32 menuFightCtrlSecretWazaTop(u8* ptr) {
    extern void* windowAllocMemory(u8* a, u32 size);
    extern void windowGetAllocPtr(u8* a);
    if ((s8)ptr[1] == 0) {
        void* dst = windowAllocMemory(ptr, 0x48);
        if (dst != NULL) {
            memcpy(dst, *(void**)(ptr + 0x60), 0x48);
        }
    }
    windowGetAllocPtr(ptr);
    return 0;
}
#pragma peephole on
#endif

/* menuFightButtonSecretMain - 0x8000FE38 | size: 0x118 */
#if 0
asm void menuFightButtonSecretMain(void) {
#include "src/game/gs_npc_interact_fn_8000FE38.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightButtonSecretMain(u8* arg1) {
    extern void* windowGetKeyInfo(void);
    extern u8 fn_801F18DC(s32 a);
    extern u8 fightFloorIsUseFightTimerCommand(s32 a);
    extern u8 fightTimerCommandIsOver(void);
    extern u16 fn_801EF634(void);
    void* data;
    u16 flags;
    s32 flag_val;
    u8 flag;
    data = windowGetKeyInfo();
    flags = *(u16*)((u8*)data + 4);
    flag_val = -1;
    if (flags & (1 << 4)) {
        flag_val = 0;
    } else if (flags & (1 << 5)) {
        flag_val = 2;
    } else if (flags & (1 << 11)) {
        flag_val = 3;
    } else if (flags & (1 << 9)) {
        arg1[0x98] = 1;
        arg1[0x99] = 1;
        *(s32*)(arg1 + 0x80) = -1;
    }
    if (flag_val >= 0) {
        arg1[0x98] = 1;
        *(s32*)(arg1 + 0x80) = flag_val;
    }
    if ((u8)fn_801F18DC(0) != 0) {
        if ((u8)fightFloorIsUseFightTimerCommand(0) == 1) {
            if ((u8)fightTimerCommandIsOver() == 1) {
                flag = 1;
                goto got_flag;
            }
        }
        if ((u16)fn_801EF634() == 1) {
            flag = 1;
            goto got_flag;
        }
    }
    flag = 0;
got_flag:
    if (flag) {
        arg1[0x98] = 1;
        arg1[0x99] = 1;
    }
}
#pragma pop
#endif

/* menuFightCtrlSecretMain - 0x8000FF50 | size: 0x58 */
#if 0
asm void menuFightCtrlSecretMain(void) {
#include "src/game/gs_npc_interact_fn_8000FF50.inc"
}
#else
#pragma peephole off
u32 menuFightCtrlSecretMain(u8* ptr) {
    extern void* windowAllocMemory(u8* a, u32 size);
    if ((s8)ptr[1] == 0) {
        void* dst = windowAllocMemory(ptr, 0x18);
        if (dst != NULL) {
            memcpy(dst, *(void**)(ptr + 0x60), 0x18);
        }
    }
    return 0;
}
#pragma peephole on
#endif

/* menuFightDrawBall - 0x8000FFA8 | size: 0x118 */
extern void jumptable_802E4D2C();
#if 0
asm void menuFightDrawBall(void) {
#include "src/game/gs_npc_interact_fn_8000FFA8.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawBall(u8* ctx, u8* npc) {
    extern u8* windowGetFreeWork(u8* a);
    u8* state;
    s32 idx;
    s32 slot;
    s32 msg;

    state = windowGetFreeWork(ctx);
    idx = *(s16*)(npc + 6) - 0x11AA;
    slot = -1;
    msg = 0;
    if ((u32)idx <= 0x17 && idx < 6) {
        slot = idx;
    }
    if (slot >= 0) {
        switch (state[slot]) {
        case 0:
            msg = 0x1B4;
            break;
        case 1:
            msg = 0x3AC;
            break;
        case 2:
            msg = 0x3AE;
            break;
        case 3:
            msg = 0x3AD;
            break;
        }
        if ((u16)msg != 0) {
            windowDrawSprite(0, 0, ctx, (u16)msg, 0);
        }
    }
}
#pragma pop
#endif

/* menuFightCtrlBall - 0x800100C0 | size: 0x68 */
#if 0
asm void menuFightCtrlBall(void) {
#include "src/game/gs_npc_interact_fn_800100C0.inc"
}
#else
#pragma peephole off
u32 menuFightCtrlBall(u8* ptr) {
    extern void* windowGetFreeWork(u8* a);
    extern void* windowGetParam(u8* a, u32 b);
    void* dst = windowGetFreeWork(ptr);
    if ((s8)ptr[1] == 0) {
        memcpy(dst, windowGetParam(ptr, 0), 6);
    }
    return 0;
}
#pragma peephole on
#endif

/* _menuFightIsUse__FP16MENU_WAZA_STATUSUs - 0x80010128 | size: 0x16c */
extern u32 fightOutPokemonCheckCanOutOkWazaBanme();
extern u32 fightOutPokemonGetSoubiItemDataId();
#if 0
asm void _menuFightIsUse__FP16MENU_WAZA_STATUSUs(void) {
#include "src/game/gs_npc_interact_fn_80010128.inc"
}
#else
#pragma push
#pragma peephole off
u32 _menuFightIsUse__FP16MENU_WAZA_STATUSUs(ctx, arg)
u8* ctx;
u16 arg;
{
    extern u32 fightOutPokemonGetPokemonPtr(void*);
    extern u32 fightOutPokemonCheckCanOutOkWazaBanme(void*, u16, s32, void*);
    extern u32 pokemonGetStatus();
    extern u32 wazaGetStatus();
    extern u32 GSmsgGetGSchar(void);
    extern u32 fightOutPokemonGetSoubiItemDataId(void*);
    u16 stackValue;
    u8* obj;
    u32 battle;
    u32 state;
    u32 result;
    u32 msg;

    obj = *(u8**)(ctx + 0x40);
    battle = fightOutPokemonGetPokemonPtr(obj);
    state = fightOutPokemonCheckCanOutOkWazaBanme(obj, arg, 1, &stackValue);
    result = pokemonGetStatus(battle, 0, 0x7F, arg);
    msg = 0;
    if ((u8)state != 0) {
        msgctrlSetValue(0x11, (s32)obj);
        msg = wazaGetStatus(0, (u16)result, 1, 0);
        msgctrlSetValue(0x28, GSmsgGetGSchar());
        fightFloorSetStatus(0, 0, 0x56, 0, (u16)fightOutPokemonGetSoubiItemDataId(obj));
    }
    switch ((u8)state) {
    case 6:
        msg = 0x7661;
        break;
    case 5:
        wazaGetStatus(0, stackValue, 1, 0);
        msgctrlSetValue(0x28, GSmsgGetGSchar());
        msg = 0x76BB;
        break;
    case 4:
        msg = 0x7600;
        break;
    case 3:
        msg = 0x75FF;
        break;
    case 2:
        msg = 0x75FE;
        break;
    case 1:
        msg = 0x75FD;
        break;
    }
    if ((u8)state == 0) {
        return 0;
    }
    return msg;
}
#pragma pop
#endif

/* menuFightDrawPP - 0x80010294 | size: 0x1e8 */
extern u32 windowGetCursor();
#if 0
asm void menuFightDrawPP(void) {
#include "src/game/gs_npc_interact_fn_80010294.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawPP(u8* ctx, u8* npc) {
    extern u8* windowGetAllocPtr(u8* a);
    extern u32 windowGetCursor(u32 val);
    extern u32 fightOutPokemonGetPokemonPtr(void*);
    extern u32 pokemonGetStatus();
    extern void fn_800FB8C8();
    u8* entries;
    u32 color;
    s32 idx;
    s32 offset;
    s32 y;
    u32 result;

    entries = windowGetAllocPtr(ctx);
    color = (u32)menuSubCalcColor(ctx, npc);
    idx = (s8)((windowGetCursor(*(u32*)(ctx + 4)) >> 16) & 0xFF);
    y = *(s16*)(npc + 0x54) - (s16)(GSmsgGetRect(0x197) >> 16);
    y = (s16)((y + ((u32)y >> 31)) >> 1);
    fn_800FB680(y, 0, color, 0x197);

    if (idx < 0 || idx >= 4) return;
    offset = idx * 0xC;
    if (*(u32*)(entries + offset + 4) == 0) return;

    result = 0;
    if (fightOutPokemonGetPokemonPtr(*(void**)(entries + 0x40)) != 0) {
        result = (u16)pokemonGetStatus(fightOutPokemonGetPokemonPtr(*(void**)(entries + 0x40)), 0, 0x7F,
                                  (s8)ctx[0x95]);
    }
    if (result == 0 || result == 0x164) {
        fn_800FB8C8(0, 0, y, *(s16*)(npc + 0x56), color, 0x2BE1);
        fn_800FB8C8(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0x2BE1);
    } else if (result == 0x165) {
        fn_800FB8C8(0, 0, y, *(s16*)(npc + 0x56), color, 0x2B6D);
        fn_800FB8C8(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0x2B6D);
    } else {
        msgctrlSetValue(0x34, *(u8*)(entries + offset + 0xF));
        fn_800FB8C8(0, 0, y, *(s16*)(npc + 0x56), color, 0xD2);
        msgctrlSetValue(0x34, *(u8*)(entries + offset + 0xE));
        fn_800FB8C8(0, 0, *(s16*)(npc + 0x54), *(s16*)(npc + 0x56), color, 0xD2);
    }
}
#pragma pop
#endif

/* menuFightDrawType - 0x8001047C | size: 0x10c */
#if 0
asm void menuFightDrawType(void) {
#include "src/game/gs_npc_interact_fn_8001047C.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawType(u8* arg1) {
    extern void* windowGetAllocPtr(u8* a);
    extern u32 windowGetCursor(u32 val);
    extern void* fightOutPokemonGetPokemonPtr(void* obj);
    extern u32 pokemonGetStatus(s32 p1, s32 p2, s32 p3, s32 p4, u16 p5, s32 p6);
    extern void msgctrlSetValue(s32 p1, s32 val);
    extern void windowDrawSprite(s32 p1, s32 p2, u8* p3, u16 p4, s32 p5);
    void* participant;
    u32 npc_data;
    s16 idx;
    s32 r30;
    u16 battle_result;
    u16 val;
    s32 temp;
    participant = windowGetAllocPtr(arg1);
    npc_data = windowGetCursor(*(u32*)(arg1 + 4));
    idx = (s16)(npc_data >> 16);
    temp = (s8)(idx & 0xFF);
    if (temp < 0 || temp >= 4) return;
    r30 = temp * 0xc;
    if (*(u32*)((u8*)participant + r30 + 4) == 0) return;
    battle_result = 0;
    if (fightOutPokemonGetPokemonPtr(*(void**)((u8*)participant + 0x40)) != 0) {
        battle_result = (u16)pokemonGetStatus(0, 0x7f, 0, 0, (s8)(*(u8*)(arg1 + 0x95)), 0);
    }
    val = 0;
    if (battle_result == 0 || battle_result == 0x164) {
        val = 0;
    } else if (battle_result < 0x166) {
        val = 0x5d;
    } else {
        val = *(u16*)((u8*)participant + r30 + 0xc);
    }
    if ((u16)val != 0) {
        windowDrawSprite(0, 2, arg1, val, 0);
    }
}
#pragma pop
#endif

/* menuFightDrawWaza - 0x80010588 | size: 0x11c */
#if 0
asm void menuFightDrawWaza(void) {
#include "src/game/gs_npc_interact_fn_80010588.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawWaza(u8* arg1, u8* arg2) {
    typedef struct {
        u32 unk_00;
        u32 value;
        u32 unk_08;
    } NpcInteractEntry;
    extern NpcInteractEntry* windowGetAllocPtr(u8* a);
    extern void* windowGetFreeWork(u8* a);
    extern void fn_800FB680(s32 a, s32 b, s32 c, u32 d);
    NpcInteractEntry* participant;
    void* npc_data;
    s32 idx;
    s16 npc_id;
    s32 offset;
    u32 result;
    participant = windowGetAllocPtr(arg1);
    npc_data = windowGetFreeWork(arg1);
    npc_id = *(s16*)(arg2 + 6);
    idx = 0;
    switch (npc_id) {
    case 0xC4:
        idx = 0;
        break;
    case 0xC5:
        idx = 1;
        break;
    case 0xC6:
        idx = 2;
        break;
    case 0xC7:
        idx = 3;
        break;
    }
    if ((s8)*((u8*)npc_data + 2) == idx) {
        windowDrawSprite(0, 0, arg1, 0x49, 0);
        windowDrawSprite(0, 0, arg1, 0x4A, 0);
    }
    offset = idx * 0xc;
    participant = (NpcInteractEntry*)((u32)participant + offset);
    result = participant->value;
    if (result != 0) {
        msgctrlSetValue(0x37, result);
        fn_800FB680(0, 0, (s32)menuSubCalcColor(arg1, arg2), 0xE7);
    }
}
#pragma pop
#endif

/* menuFightDrawCmdMsg - 0x800106A4 | size: 0x1a0 */
#if 0
asm void menuFightDrawCmdMsg(void) {
#include "src/game/gs_npc_interact_fn_800106A4.inc"
}
#else
#pragma push
#pragma peephole off
void menuFightDrawCmdMsg(u8* arg1, u8* arg2) {
    extern u32 windowGetAllocPtr(u8* a);
    extern u32 windowGetFreeWork(u8* a);
    extern u32 windowGetParam(u8* a, s32 b);
    extern void msgctrlSetValue(s32 p1, s32 val);
    extern void* fn_8001D834(u8* a, u8* b);
    extern void fn_800FB680(s32 a, s32 b, s32 c, u32 d);
    extern void* fightOutPokemonGetNicknamePtr(void* a);
    void* participant;
    void* npc_data;
    u32 r30;
    s16 npc_id;
    s32 sub;
    s32 val;
    u8* p1;
    u32 t1;
    u32 t2;
    npc_id = *(s16*)(arg2 + 6);
    r30 = 0;
    switch (npc_id) {
    case 0xb4:
        t1 = windowGetAllocPtr(arg1);
        msgctrlSetValue(0x37, (s32)t1);
        r30 = 0xcf;
        break;
    case 0x11cd:
        t2 = windowGetAllocPtr(arg1);
        msgctrlSetValue(0x36, (s32)t2);
        r30 = 0x196;
        break;
    case 0xc1:
        participant = (void*)windowGetAllocPtr(arg1);
        npc_data = (void*)windowGetFreeWork(arg1);
        sub = (s32)*(u8*)npc_data;
        switch (sub) {
        case 0:
            msgctrlSetValue(0x36, *(s32*)participant);
            r30 = 0x196;
            break;
        case 1:
            r30 = 0x199;
            break;
        }
        break;
    case 0x11d8:
        r30 = 0x196;
        val = (s32)*(u32*)(arg1 + 4);
        if (val == 0xf7) {
            msgctrlSetValue(0x36, *(s32*)windowGetAllocPtr(arg1));
        } else if (val == 0xf8) {
            p1 = (u8*)windowGetParam(arg1, 1);
            if ((u8)windowGetParam(arg1, 2) != 0) {
                msgctrlSetValue(0x36, (s32)fightOutPokemonGetNicknamePtr(p1));
            } else {
                r30 = 0x1a9;
            }
        } else {
            return;
        }
        break;
    }
    if (r30 != 0) {
        fn_800FB680(0, -2, (s32)menuSubCalcColor(arg1, arg2), r30);
    }
}
#pragma pop
#endif

/* menuFightWazaButton - 0x80010844 | size: 0x15c */
extern void pokemonWazaReplace(void);
extern void pokemonToMenuWazaStatus(void);
#if 0
asm void menuFightWazaButton(void) {
#include "src/game/gs_npc_interact_fn_80010844.inc"
}
#else
#pragma push
#pragma peephole off
u32 menuFightWazaButton(u8* ctx) {
    typedef struct MenuWindow {
        u8 pad_00[0x95];
        s8 selectedWaza;
        u8 pad_96[2];
        u8 done;
        u8 canceled;
    } MenuWindow;
    typedef struct MenuFightWazaStatus {
        u8 pad_00[0x40];
        void* outPokemon;
    } MenuFightWazaStatus;
    typedef struct MenuFightWazaWork {
        u8 mode;
        u8 unk_01;
        s8 selectedSlot;
    } MenuFightWazaWork;
    typedef struct MenuKeyInfo {
        u8 pad_00[4];
        u16 buttons;
    } MenuKeyInfo;
    extern MenuFightWazaStatus* windowGetAllocPtr(u8* a);
    extern MenuFightWazaWork* windowGetFreeWork(u8* a);
    extern MenuKeyInfo* windowGetKeyInfo(void);
    extern u32 fightOutPokemonGetPokemonPtr(void*);
    extern u32 pokemonGetStatus();
    extern void menuButtonNormal(u8* a);
    extern void pokemonWazaReplace(void*, s32, s32);
    extern void pokemonToMenuWazaStatus(void*, MenuFightWazaStatus*);
    MenuWindow* window;
    MenuFightWazaStatus* participant;
    MenuFightWazaWork* state;
    MenuKeyInfo* flagsObj;
    u32 model;
    u16 flags;
    void* saved;

    window = (MenuWindow*)ctx;
    participant = windowGetAllocPtr(ctx);
    state = windowGetFreeWork(ctx);
    model = fightOutPokemonGetPokemonPtr(participant->outPokemon);
    flagsObj = windowGetKeyInfo();
    flags = flagsObj->buttons;

    switch (state->mode) {
    case 0:
        if (model != 0 && ((u16)pokemonGetStatus(model, 0, 0x7F, window->selectedWaza) == 0x165)) {
            if ((windowGetKeyInfo()->buttons & 0x20) != 0) {
                window->done = 1;
                window->canceled = 1;
            }
        } else {
            menuButtonNormal(ctx);
        }
        break;
    case 1: {
        s32 flagBits = flags & 0xFFFF;
        if ((flagBits & 0xD0) != 0) {
            if (model != 0) {
                pokemonWazaReplace((void*)model, state->selectedSlot, window->selectedWaza);
                saved = participant->outPokemon;
                pokemonToMenuWazaStatus((void*)model, participant);
                participant->outPokemon = saved;
            }
            state->selectedSlot = -1;
            state->mode = 0;
        } else if ((flagBits & 0x20) != 0) {
            state->selectedSlot = -1;
            state->mode = 0;
        }
        break;
    }
    }
    return 0;
}
#pragma pop
#endif

/* menuFightWazaCtrl - 0x800109A0 | size: 0x190 */
extern u16 lbl_80478850[4];
#if 0
asm void menuFightWazaCtrl(void) {
#include "src/game/gs_npc_interact_fn_800109A0.inc"
}
#else
#pragma push
#pragma peephole off
u32 menuFightWazaCtrl(u8* ctx) {
    typedef struct MenuWindow {
        u8 pad_00;
        s8 state;
        u8 pad_02[2];
        u32 menuId;
        u8 pad_08[0x78];
        s32 selected;
    } MenuWindow;
    typedef struct MenuFightWazaRow {
        u32 unk_00;
        u32 wazaId;
        u32 unk_08;
    } MenuFightWazaRow;
    typedef struct MenuFightWazaWork {
        u8 mode;
        u8 unk_01;
        s8 selectedSlot;
    } MenuFightWazaWork;
    extern void* windowAllocMemory(u8* a, u32 size);
    extern u32 windowGetParam(u8* a, s32 b);
    extern MenuFightWazaWork* windowGetFreeWork(u8* a);
    extern MenuFightWazaRow* windowGetAllocPtr(u8* a);
    extern s32 menuGetCursorItemID(u32 val);
    MenuWindow* window;
    void* dst;
    MenuFightWazaWork* state;
    MenuFightWazaRow* party;
    s32 i;
    s32 id;

    window = (MenuWindow*)ctx;
    if (window->state == 0) {
        dst = windowAllocMemory(ctx, 0x48);
        if (dst != NULL) {
            memcpy(dst, (void*)windowGetParam(ctx, 0), 0x48);
        }
        state = windowGetFreeWork(ctx);
        state->mode = 0;
        state->unk_01 = 0;
        state->selectedSlot = -1;
    }

    party = windowGetAllocPtr(ctx);
    if (window->state == 5) {
        for (i = 0; i < 4; i++) {
            menuItemBiosSetSelectFlag(lbl_80478850[i], 1);
        }
    } else {
        for (i = 0; i < 4; i++) {
            if (party[i].wazaId != 0) {
                menuItemBiosSetSelectFlag(lbl_80478850[i], 1);
            } else {
                menuItemBiosSetSelectFlag(lbl_80478850[i], 0);
            }
        }
    }

    id = menuGetCursorItemID(window->menuId);
    switch (id) {
    case 0xC4:
        window->selected = 0;
        break;
    case 0xC5:
        window->selected = 1;
        break;
    case 0xC6:
        window->selected = 2;
        break;
    case 0xC7:
        window->selected = 3;
        break;
    default:
        window->selected = -1;
        break;
    }
    return 0;
}
#pragma pop
#endif

/* menuFightMainCtrl - 0x80010B30 | size: 0x168 */
#pragma push
#pragma peephole off
#pragma peephole off
u32 menuFightMainCtrl(u8* arg) {
    extern void* windowAllocMemory(u8* a, u32 size);
    extern void* windowGetAllocPtr(u8* a);
    extern s32 menuGetCursorItemID(u32 val);
    extern u8* windowSearchItemID(u8* a, s32 id);
    extern void menuItemBiosSetSelectFlag(s32 id, s32 flag);
    void* entry;
    void* participant;
    s32 trainer_id;
    u8* r;
    if ((s8)arg[1] == 0) {
        entry = windowAllocMemory(arg, 0x18);
        if (entry != NULL) {
            memcpy(entry, *(void**)(arg + 0x60), 0x18);
        }
        if (*(u8*)((u8*)entry + 0x16) != 0) {
            r = windowSearchItemID(arg, 0xB6);
            *(s32*)(r + 0x4C) = 0x13D;
            r = windowSearchItemID(arg, 0xB8);
            *(s32*)(r + 0x4C) = 0x140;
            menuItemBiosSetSelectFlag(0xB8, 1);
        } else {
            r = windowSearchItemID(arg, 0xB6);
            *(s32*)(r + 0x4C) = 0x13F;
            r = windowSearchItemID(arg, 0xB8);
            *(s32*)(r + 0x4C) = 0;
            menuItemBiosSetSelectFlag(0xB8, 0);
        }
    }
    participant = windowGetAllocPtr(arg);
    trainer_id = menuGetCursorItemID(*(u32*)(arg + 4));
    switch (trainer_id) {
    case 0xB5:
        *(s32*)(arg + 0x80) = 0;
        break;
    case 0xB6:
        if (*(u8*)((u8*)participant + 0x16) != 0) {
            *(s32*)(arg + 0x80) = 1;
        } else {
            *(s32*)(arg + 0x80) = 3;
        }
        break;
    case 0xB7:
        *(s32*)(arg + 0x80) = 2;
        break;
    case 0xB8:
        *(s32*)(arg + 0x80) = 3;
        break;
    default:
        *(s32*)(arg + 0x80) = -1;
        break;
    }
    return 0;
}
#pragma peephole on
#pragma pop

/* menuPokemonCheckPokemonChange - 0x80010C98 | size: 0x52c */
extern u32 fightOutPokemonGetTokuseiDataId(void* arg);
extern u8 fightTrainerCheckCanIrekaeFightPokemon(u32 warpId, u32 arg);
extern s32 fightPokemonGetNicknamePtr(u32 arg);
extern void GSlogWrite(const char* fmt, ...);
extern u8 lbl_80266788[];
extern u8 lbl_802E4B78[];
#if 0
asm void menuPokemonCheckPokemonChange(void) {
#include "src/game/gs_npc_interact_fn_80010C98.inc"
}
#else
#pragma peephole off
u32 menuPokemonCheckPokemonChange(void* npc, u32 warpId, u32 variant) {
#define WAIT_FOR_DIALOG(waitLabel, checkLabel, haveLabel, doneLabel) \
    goto checkLabel; \
waitLabel: \
    advance = fn_801F18DC(0); \
    if (advance != 0) { \
        if ((fightFloorIsUseFightTimerCommand(0) == 1) && (fightTimerCommandIsOver() == 1)) { \
            advance = 1; \
            goto haveLabel; \
        } else if (fn_801EF634() == 1) { \
            advance = 1; \
            goto haveLabel; \
        } \
    } \
    advance = 0; \
haveLabel: \
    if (advance != 0) { \
        goto doneLabel; \
    } \
    _threadSwitch(); \
checkLabel: \
    inputFlags = fn_800F7AF0(1); \
    maskedFlags = fn_800F7BC4(1); \
    maskedFlags &= inputFlags; \
    if ((maskedFlags & 0x300) == 0) { \
        goto waitLabel; \
    } \
doneLabel:

    void* linkedNpc;
    u32 inputFlags;
    u32 maskedFlags;
    u8 relation;
    u8 advance;
    u8 kind;

    relation = fightFloorCheckFightActionFightOutPokemonIrekaeSelect(0, npc, &linkedNpc);
    if (relation == 1) {
        msgctrlSetValue(0xD, (s32)fightOutPokemonGetNicknamePtr(npc));
        winMsgOpen(1, 0x76FB, 1, 0);
        WAIT_FOR_DIALOG(waitRelationOne, checkRelationOne, haveRelationOne, doneRelationOne);
        winMsgClose(1);
        return 0;
    }
    if (relation == 2) {
        fightFloorSetStatus(0, 0, 0x57, 0, (u16)fightOutPokemonGetTokuseiDataId(linkedNpc));
        msgctrlSetValue(0xD, (s32)fightOutPokemonGetNicknamePtr(linkedNpc));
        msgctrlSetValue(0xE, (s32)fightOutPokemonGetNicknamePtr(npc));
        winMsgOpen(1, 0x761F, 1, 0);
        WAIT_FOR_DIALOG(waitRelationTwo, checkRelationTwo, haveRelationTwo, doneRelationTwo);
        winMsgClose(1);
        return 0;
    }
    if (warpId == 0) {
        warpId = fightFloorGetGcHeroFightTrainerPtr(0);
    }
    if (warpId == 0) {
        return 0;
    }
    variant = fightTrainerGetValidFightPokemonPtr(warpId, (u16)variant);
    if (variant == 0) {
        return 0;
    }
    kind = fightTrainerCheckCanIrekaeFightPokemon(warpId, variant);
    if (kind == 1) {
        msgctrlSetValue(0xD, fightPokemonGetNicknamePtr(variant));
        winMsgOpen(1, 0x76FE, 1, 0);
        WAIT_FOR_DIALOG(waitKindOne, checkKindOne, haveKindOne, doneKindOne);
        winMsgClose(1);
        return 0;
    }
    if (kind == 2) {
        msgctrlSetValue(0xD, fightPokemonGetNicknamePtr(variant));
        winMsgOpen(1, 0x76FC, 1, 0);
        WAIT_FOR_DIALOG(waitKindTwo, checkKindTwo, haveKindTwo, doneKindTwo);
        winMsgClose(1);
        return 0;
    }
    if (kind == 3) {
        msgctrlSetValue(0xD, fightPokemonGetNicknamePtr(variant));
        winMsgOpen(1, 0x76FD, 1, 0);
        WAIT_FOR_DIALOG(waitKindThree, checkKindThree, haveKindThree, doneKindThree);
        winMsgClose(1);
        return 0;
    }
    if (kind == 0) {
        return 1;
    }
    GSlogWrite((const char*)lbl_80266788, (const char*)lbl_802E4B78);
#undef WAIT_FOR_DIALOG
    return 0;
}
#pragma peephole on
#endif
