/**
 * @file sdk_range_800A37CC.c
 * @brief Residual SDK math range, 0x800A37CC - 0x800A3EB0.
 */

#if !defined(SDK_800A37CC_MODE_VECTOR_ONLY) && \
    !defined(SDK_800A37CC_MODE_PSQUAT_ONLY) && \
    !defined(SDK_800A37CC_MODE_CQUATROT_ONLY) && \
    !defined(SDK_800A37CC_MODE_CQUATSLERP_ONLY)
#define SDK_800A37CC_MODE_MTXVEC_ONLY
#endif

#define SDK_800A37CC_SUFFIX_ACTIVE

#if defined(SDK_800A37CC_MODE_MTXVEC_ONLY)
#define SDK_POST_MTXVEC_EXCLUDE
#elif defined(SDK_800A37CC_MODE_VECTOR_ONLY)
#define SDK_QUAT_SUFFIX_EXCLUDE
#define SDK_CQUATSLERP_EXCLUDE
#define SDK_MTXVEC_PREFIX_EXCLUDE
#define SDK_PROJECTION_PREFIX_EXCLUDE
#elif defined(SDK_800A37CC_MODE_PSQUAT_ONLY)
#define SDK_MTXVEC_PREFIX_EXCLUDE
#define SDK_PROJECTION_PREFIX_EXCLUDE
#define SDK_VECTOR_PREFIX_EXCLUDE
#define SDK_CQUATROT_EXCLUDE
#define SDK_CQUATSLERP_EXCLUDE
#elif defined(SDK_800A37CC_MODE_CQUATROT_ONLY)
#define SDK_MTXVEC_PREFIX_EXCLUDE
#define SDK_PROJECTION_PREFIX_EXCLUDE
#define SDK_VECTOR_PREFIX_EXCLUDE
#define SDK_PSQUAT_MULTIPLY_EXCLUDE
#define SDK_CQUATSLERP_EXCLUDE
#elif defined(SDK_800A37CC_MODE_CQUATSLERP_ONLY)
#define SDK_CQUATSLERP_ONLY
#endif

#include "src/dolphin/sdk_range_800A2D38.c"
