#!/usr/bin/env python3
"""surgical_report_update.py — mark a known set of trust-gated 100% functions
in report.json WITHOUT a full local rebuild.

Why: the local build/measure env is incomplete (effect_visual not in objdiff.json,
HSD W-SDA-WRAPPER TUs don't compile), so a naive gen_decomp_report regen DROPS
~63 functions that the committed report legitimately counts. We instead start
from the committed baseline and flip ONLY the functions we band-verified at 100%
this run, recomputing the affected units + the top-level aggregate.

Usage: python tools/decomp_work/surgical_report_update.py <fns_file> [report.json]
  <fns_file> = newline-separated fn_ names that are now 100% byte-exact.
"""
import json
import sys
from pathlib import Path

MATCH = 99.995  # treat >= as 100% matched
ROOT = Path(__file__).resolve().parents[2]
BUILD_CFG = ROOT / "build" / "GC6E01" / "config.json"


def ci(v):  # code value -> int (schema stores as string)
    return int(v or 0)


def pct(num, den):
    return (100.0 * num / den) if den else 0.0


def prune(d):
    return {k: v for k, v in d.items() if v is not None}


def data_units_from_build_config():
    try:
        cfg = json.loads(BUILD_CFG.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []

    raw_units = list(cfg.get("units", []) or [])
    for module in cfg.get("modules", []) or []:
        raw_units.extend(module.get("units", []) or [])

    units = []
    for u in raw_units:
        size = ci(u.get("data_size"))
        if size <= 0:
            continue
        auto_generated = bool(u.get("autogenerated"))
        complete = bool(u.get("complete"))
        matched = size if (auto_generated or complete) else 0
        completed = size if complete else 0
        name = u.get("name") or Path(u.get("object", "data")).stem
        measures = {
            "fuzzy_match_percent": 100.0 if matched == size else 0.0,
            "total_data": str(size),
            "matched_data": str(matched) if matched else None,
            "matched_data_percent": pct(matched, size) if matched else None,
            "complete_data": str(completed) if completed else None,
            "complete_data_percent": pct(completed, size) if completed else None,
            "total_units": 1,
            "complete_units": 1 if complete else None,
        }
        metadata = prune({
            "complete": True if complete else None,
            "auto_generated": True if auto_generated else None,
            "source_path": u.get("object"),
        })
        units.append(prune({
            "name": name,
            "measures": prune(measures),
            "sections": [{
                "name": name,
                "size": str(size),
                "fuzzy_match_percent": 100.0 if matched == size else 0.0,
            }],
            "functions": [],
            "metadata": metadata if metadata else None,
        }))
    return units


def is_data_unit(u):
    m = u.get("measures", {}) or {}
    return ci(m.get("total_data")) > 0 and ci(m.get("total_code")) == 0


def recompute_unit(u):
    fns = u.get("functions", [])
    m = u["measures"]
    total_code = ci(m.get("total_code"))
    matched_code = sum(ci(f.get("size")) for f in fns if f.get("fuzzy_match_percent", 0) >= MATCH)
    matched_fns = sum(1 for f in fns if f.get("fuzzy_match_percent", 0) >= MATCH)
    total_fns = int(m.get("total_functions", len(fns)) or 0)
    # code-weighted fuzzy
    if total_code:
        fuzzy = sum(ci(f.get("size")) * f.get("fuzzy_match_percent", 0) for f in fns) / total_code
    else:
        fuzzy = 0.0
    m["matched_code"] = str(matched_code)
    m["matched_code_percent"] = (100.0 * matched_code / total_code) if total_code else 0.0
    m["matched_functions"] = matched_fns
    m["matched_functions_percent"] = (100.0 * matched_fns / total_fns) if total_fns else 0.0
    m["fuzzy_match_percent"] = fuzzy
    unit_complete = bool(total_fns and matched_fns == total_fns)
    if unit_complete:
        m["complete_code"] = str(total_code)
        m["complete_code_percent"] = 100.0
        m["complete_units"] = 1
        u.setdefault("metadata", {})["complete"] = True
    else:
        m.pop("complete_code", None)
        m.pop("complete_code_percent", None)
        m.pop("complete_units", None)
        if u.get("metadata"):
            u["metadata"].pop("complete", None)
    return u


def main():
    fns_file = sys.argv[1]
    report = sys.argv[2] if len(sys.argv) > 2 else "report.json"
    crk = set(Path(fns_file).read_text().split())
    d = json.loads(Path(report).read_text(encoding="utf-8"))
    d["version"] = 2

    touched = set()
    flipped = 0
    code_units = [u for u in d["units"] if not is_data_unit(u)]
    for u in code_units:
        unit_hit = False
        for f in u.get("functions", []):
            if f["name"] in crk and f.get("fuzzy_match_percent", 0) < MATCH:
                f["fuzzy_match_percent"] = 100.0
                flipped += 1
                unit_hit = True
        if unit_hit:
            touched.add(u["name"])
        recompute_unit(u)
    data_units = data_units_from_build_config()
    d["units"] = data_units + code_units

    # top-level aggregate = sum of units
    units = d["units"]
    T = d["measures"]
    tot_code = sum(ci(u["measures"].get("total_code")) for u in units)
    mat_code = sum(ci(u["measures"].get("matched_code")) for u in units)
    cmp_code = sum(ci(u["measures"].get("complete_code")) for u in units)
    tot_data = sum(ci(u["measures"].get("total_data")) for u in units)
    mat_data = sum(ci(u["measures"].get("matched_data")) for u in units)
    cmp_data = sum(ci(u["measures"].get("complete_data")) for u in units)
    tot_fns = sum(int(u["measures"].get("total_functions", 0) or 0) for u in units)
    mat_fns = sum(int(u["measures"].get("matched_functions", 0) or 0) for u in units)
    cmp_units = sum(int(u["measures"].get("complete_units", 0) or 0) for u in units)
    fuzzy = (sum(ci(u["measures"].get("total_code")) * u["measures"].get("fuzzy_match_percent", 0)
                 for u in units) / tot_code) if tot_code else 0.0
    T["total_code"] = str(tot_code)
    T["matched_code"] = str(mat_code)
    T["matched_code_percent"] = (100.0 * mat_code / tot_code) if tot_code else 0.0
    T["complete_code"] = str(cmp_code)
    T["complete_code_percent"] = (100.0 * cmp_code / tot_code) if tot_code else 0.0
    T["total_data"] = str(tot_data)
    T["matched_data"] = str(mat_data)
    T["matched_data_percent"] = (100.0 * mat_data / tot_data) if tot_data else 0.0
    if cmp_data:
        T["complete_data"] = str(cmp_data)
        T["complete_data_percent"] = (100.0 * cmp_data / tot_data) if tot_data else 0.0
    else:
        T.pop("complete_data", None)
        T.pop("complete_data_percent", None)
    T["total_functions"] = tot_fns
    T["matched_functions"] = mat_fns
    T["matched_functions_percent"] = (100.0 * mat_fns / tot_fns) if tot_fns else 0.0
    T["fuzzy_match_percent"] = fuzzy
    T["total_units"] = len(units)
    T["complete_units"] = cmp_units

    # match gen_decomp_report.py's minified, no-space encoding so the diff is clean
    Path(report).write_text(json.dumps(d, separators=(",", ":")), encoding="utf-8")
    print(f"flipped {flipped} functions across {len(touched)} units: {sorted(touched)}")
    print(f"TOP: {mat_fns}/{tot_fns} fn ({T['matched_functions_percent']:.2f}%), "
          f"{T['matched_code_percent']:.2f}% code")


if __name__ == "__main__":
    main()
