#!/usr/bin/env python3
"""Sync README.md's Status section from the committed decomp.dev report.json."""

from __future__ import annotations

import datetime as _dt
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
REPORT = os.path.join(ROOT, "report.json")
README = os.path.join(ROOT, "README.md")


def fl(measures: dict, key: str) -> float:
    try:
        return float(measures.get(key, 0) or 0)
    except (TypeError, ValueError):
        return 0.0


def integer(measures: dict, key: str) -> int:
    return int(fl(measures, key))


def pct(num: int, den: int) -> float:
    return (100.0 * num / den) if den else 0.0


def mb(num: int) -> str:
    return f"{num / 1_000_000:.2f} MB"


def bar(percent: float, width: int = 24) -> str:
    filled = max(0, min(width, round(width * percent / 100.0)))
    return "`[" + ("#" * filled) + ("-" * (width - filled)) + "]`"


def status_block(measures: dict, date: str) -> str:
    total_code = integer(measures, "total_code")
    matched_code = integer(measures, "matched_code")
    complete_code = integer(measures, "complete_code")
    total_data = integer(measures, "total_data")
    matched_data = integer(measures, "matched_data")
    complete_data = integer(measures, "complete_data")
    total_functions = integer(measures, "total_functions")
    matched_functions = integer(measures, "matched_functions")

    decompiled = fl(measures, "fuzzy_match_percent")
    linked_total = total_code + total_data
    linked_done = complete_code + complete_data
    fully_linked = pct(linked_done, linked_total)
    code_matched = pct(matched_code, total_code)
    code_linked = pct(complete_code, total_code)
    data_matched = pct(matched_data, total_data)
    data_linked = pct(complete_data, total_data)
    fn_match = pct(matched_functions, total_functions)

    return f"""## Status

**Pokémon Colosseum is {decompiled:.2f}% decompiled**

**{fully_linked:.2f}% fully linked**

| Segment | Matched | Fully linked | Detail |
|---|---:|---:|---|
| Code ({mb(total_code)}) | {bar(code_matched)} {code_matched:.2f}% | {bar(code_linked)} {code_linked:.2f}% | {matched_code:,} / {total_code:,} matched bytes; {matched_functions:,} / {total_functions:,} functions ({fn_match:.2f}%) |
| Data ({mb(total_data)}) | {bar(data_matched)} {data_matched:.2f}% | {bar(data_linked)} {data_linked:.2f}% | {matched_data:,} / {total_data:,} matched bytes |

Last measured {date} with `python tools/gen_decomp_report.py -o report.json`.
The committed `report.json` is the decomp.dev source of truth; it contains
progress metadata only, not ROM bytes or extracted assets. Autogenerated data
is shown as matched metadata, not completed handwritten source.

"""


def main() -> int:
    if not (os.path.exists(REPORT) and os.path.exists(README)):
        return 0
    measures = json.load(open(REPORT, encoding="utf-8")).get("measures", {})
    if not integer(measures, "total_code"):
        return 0
    date = sys.argv[1] if len(sys.argv) > 1 else _dt.date.today().isoformat()
    txt = open(README, encoding="utf-8").read()
    block = status_block(measures, date)
    new = re.sub(r"## Status\n.*?(?=## You will need\n)", block, txt, flags=re.S)
    if new == txt:
        print("README already current")
        return 0
    open(README, "w", encoding="utf-8").write(new)
    print("README updated from report.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
