#!/usr/bin/env python3
"""pcport_genfont.py -- generate an embedded ASCII bitmap-font atlas header.

Renders printable ASCII (0x20..0x7E) with a system monospace TTF into a fixed
16-column cell grid, and emits pcport/pcport_font.h: cell/atlas dimensions +
a flat alpha-coverage array (one byte per atlas pixel). The PC port has no glyph
renderer; pcport_main.c expands this to an RGBA (white + alpha) texture once and
draws text by blitting per-glyph sub-rects (DrawTextScreen).

Run: python tools/pcport_genfont.py
"""
from pathlib import Path
from PIL import Image, ImageFont, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "pcport" / "pcport_font.h"

FIRST, LAST = 0x20, 0x7E          # space .. '~'
COLS = 16
CELL_W, CELL_H = 16, 24
FONT_PX = 20                      # rendered glyph size inside the cell

FONT_CANDIDATES = [
    r"C:\Windows\Fonts\consola.ttf",   # Consolas (crisp monospace)
    r"C:\Windows\Fonts\cour.ttf",      # Courier New
    r"C:\Windows\Fonts\lucon.ttf",     # Lucida Console
]


def load_font():
    for p in FONT_CANDIDATES:
        if Path(p).exists():
            return ImageFont.truetype(p, FONT_PX), p
    return ImageFont.load_default(), "PIL-default"


def main():
    font, used = load_font()
    n = LAST - FIRST + 1
    rows = (n + COLS - 1) // COLS
    aw, ah = COLS * CELL_W, rows * CELL_H
    atlas = Image.new("L", (aw, ah), 0)
    draw = ImageDraw.Draw(atlas)

    for i in range(n):
        ch = chr(FIRST + i)
        cx, cy = (i % COLS) * CELL_W, (i // COLS) * CELL_H
        # centre the glyph horizontally in the cell, small top pad
        try:
            bbox = draw.textbbox((0, 0), ch, font=font)
            gw = bbox[2] - bbox[0]
            ox = cx + max(0, (CELL_W - gw) // 2) - bbox[0]
        except Exception:
            ox = cx + 2
        draw.text((ox, cy + 1), ch, fill=255, font=font)

    data = atlas.tobytes()  # row-major, one byte/pixel
    lines = []
    lines.append("/* AUTO-GENERATED by tools/pcport_genfont.py -- do not edit by hand. */")
    lines.append(f"/* Source font: {used} @ {FONT_PX}px */")
    lines.append("#ifndef PCPORT_FONT_H")
    lines.append("#define PCPORT_FONT_H")
    lines.append(f"#define PCPORT_FONT_FIRST   {FIRST}")
    lines.append(f"#define PCPORT_FONT_LAST    {LAST}")
    lines.append(f"#define PCPORT_FONT_COLS    {COLS}")
    lines.append(f"#define PCPORT_FONT_CELL_W  {CELL_W}")
    lines.append(f"#define PCPORT_FONT_CELL_H  {CELL_H}")
    lines.append(f"#define PCPORT_FONT_ATLAS_W {aw}")
    lines.append(f"#define PCPORT_FONT_ATLAS_H {ah}")
    lines.append(f"static const unsigned char kPcportFontAlpha[{aw} * {ah}] = {{")
    for off in range(0, len(data), 24):
        chunk = data[off:off + 24]
        lines.append("    " + ",".join(str(b) for b in chunk) + ",")
    lines.append("};")
    lines.append("#endif /* PCPORT_FONT_H */")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({aw}x{ah} atlas, {len(data)} alpha bytes, font={used})")


if __name__ == "__main__":
    main()
