#!/usr/bin/env bash
# decomp.sh — one-stop wrapper for the common Colosseum matching-decomp operations,
# so a new agent never reimplements the toolchain. Read AGENT_ONBOARDING.md first.
#
# Subcommands:
#   decomp.sh measure <file_or_stem> <fn...>   authoritative per-fn match% (match_scan_file)
#   decomp.sh next    [file_or_stem]           list next non-100% targets (Equivalent pool, excl. walls)
#   decomp.sh asm     <fn>                      print the target asm (the <stem>_fn_<addr>.inc)
#   decomp.sh where   <fn>                      which src/*.c file owns this fn
#   decomp.sh walls   <fn>                      grep WALLS.md + equivalent.txt for a fn (is it a logged wall?)
#   decomp.sh band    <args...>                 big-file parallel-agent band harness (-> band.py; see AGENT_ONBOARDING.md)
#
# Notes:
#   * Uses PATH python3 by default; set $WINPY if your `python` is a stub/WSL shim.
#   * Never edits *_fn_*.inc, #if0->#if1, or symbols.build.txt — read-only helpers.
#   * `measure` is the ONE authoritative command; always re-measure, never self-assert a %.

set -uo pipefail

# --- locate repo root (this script lives at tools/decomp_work/decomp.sh) ---
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SELF/../.." && pwd)"

# --- python interpreter: default to PATH python3/python (cross-platform).
#     Override with $WINPY when PATH `python` is a stub/WSL shim (e.g. on Windows,
#     point it at C:/.../Python312/python.exe). ---
WINPY="${WINPY:-$(command -v python3 || command -v python || echo python3)}"
if [ ! -x "$WINPY" ] && ! command -v "$WINPY" >/dev/null 2>&1; then
  WINPY="$(command -v python3 || command -v python || echo python3)"
fi

WALLS="$ROOT/WALLS.md"
EQUIV="$ROOT/tools/decomp_work/equivalent.txt"
EQUIV_POOL="$ROOT/tools/decomp_work/equiv_pool.txt"

usage() {
  sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

# Resolve a file stem or path to a tracked src/**.c (mirrors match_scan_file.resolve).
resolve_src() {
  local name="$1" p
  p="$name"
  case "$p" in
    /*|[A-Za-z]:*) : ;;            # absolute already
    *) [ -f "$ROOT/$p" ] && p="$ROOT/$p" ;;
  esac
  if [ -f "$p" ]; then printf '%s\n' "$p"; return 0; fi
  # stem search under src/
  local stem; stem="$(basename "$name" .c)"
  find "$ROOT/src" -name "$stem.c" 2>/dev/null | head -1
}

cmd_measure() {
  [ $# -ge 2 ] || { echo "usage: decomp.sh measure <file_or_stem> <fn...>" >&2; return 2; }
  local file="$1"; shift
  ( cd "$ROOT" && "$WINPY" tools/match_scan_file.py "$file" "$@" )
}

cmd_asm() {
  [ $# -ge 1 ] || { echo "usage: decomp.sh asm <fn>" >&2; return 2; }
  local fn="$1"
  # *_fn_*.inc lives next to its source as <stem>_fn_<ADDR>.inc
  local hits; hits="$(find "$ROOT/src" -name "*_${fn}.inc" 2>/dev/null)"
  if [ -z "$hits" ]; then
    echo "No <stem>_${fn}.inc found." >&2
    echo "  -> $fn has no asm form (it is fully decompiled REAL_C, or the addr is wrong)." >&2
    echo "  -> To read the active C/asm, open its source file (try: decomp.sh walls $fn)." >&2
    return 1
  fi
  local f
  for f in $hits; do
    echo "===== ${f#$ROOT/} ====="
    cat "$f"
  done
}

cmd_where() {
  [ $# -ge 1 ] || { echo "usage: decomp.sh where <fn>" >&2; return 2; }
  local fn="$1" found=1
  # 1) fastest: the asm form's .inc sits next to the source as <stem>_fn_<ADDR>.inc
  local inc
  for inc in $(find "$ROOT/src" -name "*_${fn}.inc" 2>/dev/null); do
    local dir base stem
    dir="$(dirname "$inc")"; base="$(basename "$inc")"
    stem="${base%%_${fn}.inc}"
    if [ -f "$dir/$stem.c" ]; then
      echo "${dir#$ROOT/}/$stem.c   (has asm form: ${inc#$ROOT/})"
      found=0
    fi
  done
  # 2) else grep for the active C definition
  if [ $found -ne 0 ]; then
    local g
    g="$(grep -rls -- "$fn" --include='*.c' "$ROOT/src" 2>/dev/null | head -3)"
    if [ -n "$g" ]; then
      echo "$g" | sed "s|$ROOT/||;s|^|  (defines/uses) |"
      found=0
    fi
  fi
  [ $found -eq 0 ] || { echo "not found in src/**.c: $fn" >&2; return 1; }
}

cmd_walls() {
  [ $# -ge 1 ] || { echo "usage: decomp.sh walls <fn>" >&2; return 2; }
  local fn="$1" found=1
  echo "===== WALLS.md ====="
  if grep -n -- "$fn" "$WALLS" 2>/dev/null; then found=0; fi
  echo "===== equivalent.txt (logged Equivalent => HARD-SKIP) ====="
  if grep -n -- "$fn" "$EQUIV" 2>/dev/null; then found=0; fi
  echo "===== equiv_pool.txt (near-miss list, with current %) ====="
  grep -n -- "$fn" "$EQUIV_POOL" 2>/dev/null || true
  if [ $found -ne 0 ]; then
    echo "(not in WALLS.md or equivalent.txt — not a logged wall; fair game to attack)"
  fi
}

cmd_band() {
  # Passthrough to the file-parameterized band harness (private-scratch, parallel agents).
  ( cd "$ROOT" && "$WINPY" tools/decomp_work/band.py "$@" )
}

cmd_next() {
  # List next non-100% REAL_C targets (the Equivalent pool), EXCLUDING logged walls.
  # Reuses the cached equiv_pool.txt (generated by progress2.py --measure --list-equiv);
  # regenerate it with:  decomp.sh next --refresh
  local filter="${1:-}"
  if [ "$filter" = "--refresh" ]; then
    echo "Regenerating equiv_pool.txt (progress2.py --measure, slow)..." >&2
    ( cd "$ROOT" && "$WINPY" tools/decomp_work/progress2.py --measure \
        --list-equiv tools/decomp_work/equiv_pool.txt ) || return 1
    filter=""
  fi
  if [ ! -f "$EQUIV_POOL" ]; then
    echo "No equiv_pool.txt yet. Run: decomp.sh next --refresh" >&2
    return 1
  fi
  # logged walls/equivalents to exclude (first token per non-comment line)
  local walls_tmp; walls_tmp="$(mktemp)"
  awk -F'#' 'NF{gsub(/[ \t]/,"",$1); if($1!="") print $1}' "$EQUIV" 2>/dev/null | sort -u > "$walls_tmp"
  echo "# next non-100% targets (Equivalent pool, closest-first, logged walls removed)"
  echo "# fn            match%   (file via: decomp.sh walls <fn> / grep src)"
  awk 'NF && $1 !~ /^#/' "$EQUIV_POOL" \
    | grep -v -F -w -f "$walls_tmp" 2>/dev/null \
    | { if [ -n "$filter" ]; then grep -i -- "$filter"; else cat; fi; } \
    | head -40
  rm -f "$walls_tmp"
}

main() {
  [ $# -ge 1 ] || usage 1
  local sub="$1"; shift
  case "$sub" in
    measure|m) cmd_measure "$@" ;;
    next|n)    cmd_next "$@" ;;
    asm|a)     cmd_asm "$@" ;;
    where|whereis) cmd_where "$@" ;;
    walls|w)   cmd_walls "$@" ;;
    band|b)    cmd_band "$@" ;;
    -h|--help|help) usage 0 ;;
    *) echo "unknown subcommand: $sub" >&2; usage 1 ;;
  esac
}

main "$@"
