#!/usr/bin/env python3
"""check_report_sanity.py - guard report.json against phantom/scratch units.

The decomp.dev progress metric (report.json) is generated by scanning every
base object in build/GC6E01/base/. The band harness + band_integrate.py drop
TRANSIENT scratch objects there (band_*, *_integrated, _int_*, _evt_*, cs_*).
If those get counted as real translation units they become PHANTOM units that
duplicate a real TU and inflate total_functions — which silently dropped the
published code% from ~53% to ~44% on 2026-06-16 (the band_trainer_integrated /
manual_integrated / band_mtool incident: +783 phantom functions) even though
the DOL still byte-matched the ROM.

This check fails CI if report.json contains any scratch-pattern unit, so a
polluted report can never be merged again. It also cross-checks that the
top-level total_functions equals the sum over units (no hidden inflation).

Usage:  python tools/check_report_sanity.py [path/to/report.json]
Exit 0 = clean, 1 = violation.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Keep this pattern in sync with tools/progress.py:SKIP_BASE_SCRATCH.
SCRATCH = re.compile(
    r"^(band_|manual_integrated|_int_|_evt_|cs_)|_integrated$",
    re.IGNORECASE,
)


def main(argv: list[str]) -> int:
    path = Path(argv[1]) if len(argv) > 1 else Path("report.json")
    if not path.exists():
        print(f"report-sanity: {path} not found — nothing to check", file=sys.stderr)
        return 0

    report = json.loads(path.read_text(encoding="utf-8"))
    units = report.get("units", []) or []
    measures = report.get("measures", {}) or {}

    problems: list[str] = []

    # 1) No scratch/phantom units.
    scratch = [u.get("name", "?") for u in units if SCRATCH.search(u.get("name", ""))]
    if scratch:
        problems.append(
            "phantom/scratch units present in report.json (band-harness leakage): "
            + ", ".join(sorted(scratch))
            + "\n  Fix: remove build/GC6E01/base/<that>.o and regenerate "
            "(tools/progress.py skips these via SKIP_BASE_SCRATCH)."
        )

    # 2) Top-level total_functions must equal the sum over units (no hidden inflation).
    def mint(value) -> int:
        try:
            return int(float(value))
        except (TypeError, ValueError):
            return 0

    def usum(key: str) -> int:
        total = 0
        for u in units:
            total += mint((u.get("measures", {}) or {}).get(key, 0))
        return total

    summed = usum("total_functions")
    declared = mint(measures.get("total_functions", 0))
    if declared and summed and declared != summed:
        problems.append(
            f"measures.total_functions ({declared}) != sum over units ({summed}) "
            "— aggregate is out of sync with the unit list."
        )

    # 2b) The decomp.dev report must carry the non-code loadable data
    #     denominator, otherwise the second Code/Data progress bar disappears.
    total_data = mint(measures.get("total_data", 0))
    matched_data = mint(measures.get("matched_data", 0))
    complete_data = mint(measures.get("complete_data", 0))
    if total_data <= 0:
        problems.append(
            "measures.total_data is missing or zero — report.json will not "
            "render the decomp.dev Data progress bar."
        )
    if matched_data > total_data:
        problems.append(
            f"measures.matched_data ({matched_data}) exceeds total_data ({total_data})."
        )
    if complete_data > total_data:
        problems.append(
            f"measures.complete_data ({complete_data}) exceeds total_data ({total_data})."
        )

    # 3) Phantom double-count detection. A band/scratch phantom is a COPY of a real
    #    TU, so it carries BOTH the same (total, matched) counts AND (nearly) the same
    #    function set. Require both signals: the counts are a cheap pre-filter, the
    #    function-set overlap confirms it is genuinely the same TU. This avoids two
    #    false positives: (a) different TUs that share counts by coincidence
    #    (gs_task and people.c can both be 49/53), and (b) pre-existing near-duplicate
    #    measurement units whose counts already differ (gs_field_world / gs_render_w2).
    by_sig: dict[tuple[int, int], list[tuple[str, frozenset]]] = {}
    for u in units:
        m = u.get("measures", {}) or {}
        sig = (int(m.get("total_functions", 0) or 0), int(m.get("matched_functions", 0) or 0))
        if sig[0] < 50:
            continue
        names = frozenset(f.get("name", "") for f in (u.get("functions", []) or []))
        for prev_name, prev_set in by_sig.get(sig, []):
            union = len(names | prev_set)
            jaccard = (len(names & prev_set) / union) if union else 0.0
            if jaccard >= 0.8:
                problems.append(
                    f"duplicate unit signature {sig} with {jaccard:.0%} function-set "
                    f"overlap shared by '{prev_name}' and '{u.get('name')}' — "
                    "likely a double-counted TU."
                )
                break
        by_sig.setdefault(sig, []).append((u.get("name", "?"), names))

    # 4) If checking the committed root report, also require the README and
    #    agent-lane progress.json to be synchronized with it.
    if path.resolve() == (ROOT / "report.json").resolve():
        sync = subprocess.run(
            [sys.executable, "tools/sync_progress_metadata.py", "--check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if sync.returncode != 0:
            problems.append(
                "progress metadata is stale relative to report.json:\n"
                + (sync.stdout + sync.stderr).strip()
            )

    if problems:
        print("report-sanity: FAIL", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        return 1

    print(
        f"report-sanity: OK ({len(units)} units, "
        f"total_functions={declared or summed}, "
        f"code%={measures.get('matched_code_percent', 0):.2f}, "
        f"data={matched_data}/{total_data})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
