#!/usr/bin/env python3
"""check_report_sanity.py - guard report.json against phantom/scratch units.

The decomp.dev progress metric (report.json) is generated by scanning every
base object in build/GC6E01/base/. The band harness + band_integrate.py drop
TRANSIENT scratch objects there (band_*, *_integrated, _int_*, _evt_*, cs_*).
If those get counted as real translation units they become PHANTOM units that
duplicate a real TU and inflate total_functions — which silently dropped the
published code% from ~53% to ~44% on 2026-06-16 (the band_trainer_integrated /
manual_integrated / band_mtool incident: +783 phantom functions) even though
the DOL still byte-matched the ROM.

This check fails CI if report.json contains any scratch-pattern unit, so a
polluted report can never be merged again. It also cross-checks that the
top-level total_functions/total_code values equal the sum over units (no hidden
inflation or hidden denominator shrink).

Usage:  python tools/check_report_sanity.py [path/to/report.json]
Exit 0 = clean, 1 = violation.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_PROGRESS = ROOT / "config" / "GC6E01" / "data_progress.json"
DATA_VERIFIER = ROOT / "tools" / "verify_data_progress.py"
BUILD_CFG = ROOT / "build" / "GC6E01" / "config.json"
OBJCOPY = ROOT / "build" / "binutils" / "powerpc-eabi-objcopy"
MATCH = 99.995

# Keep this pattern in sync with tools/progress.py:SKIP_BASE_SCRATCH.
SCRATCH = re.compile(
    r"^(band_|manual_integrated|_int_|_evt_|cs_)|_integrated$",
    re.IGNORECASE,
)


def main(argv: list[str]) -> int:
    path = Path(argv[1]) if len(argv) > 1 else Path("report.json")
    if not path.exists():
        print(f"report-sanity: {path} not found — nothing to check", file=sys.stderr)
        return 0

    report = json.loads(path.read_text(encoding="utf-8"))
    units = report.get("units", []) or []
    measures = report.get("measures", {}) or {}

    problems: list[str] = []

    # 1) No scratch/phantom units.
    scratch = [u.get("name", "?") for u in units if SCRATCH.search(u.get("name", ""))]
    if scratch:
        problems.append(
            "phantom/scratch units present in report.json (band-harness leakage): "
            + ", ".join(sorted(scratch))
            + "\n  Fix: remove build/GC6E01/base/<that>.o and regenerate "
            "(tools/progress.py skips these via SKIP_BASE_SCRATCH)."
        )

    # 2) Top-level total_functions must equal the sum over units (no hidden inflation).
    def mint(value) -> int:
        try:
            return int(float(value))
        except (TypeError, ValueError):
            return 0

    def mfloat(value) -> float:
        try:
            return float(value or 0)
        except (TypeError, ValueError):
            return 0.0

    def usum(key: str) -> int:
        total = 0
        for u in units:
            total += mint((u.get("measures", {}) or {}).get(key, 0))
        return total

    summed = usum("total_functions")
    declared = mint(measures.get("total_functions", 0))
    if declared and summed and declared != summed:
        problems.append(
            f"measures.total_functions ({declared}) != sum over units ({summed}) "
            "— aggregate is out of sync with the unit list."
        )

    summed_code = usum("total_code")
    declared_code = mint(measures.get("total_code", 0))
    if declared_code and summed_code and declared_code != summed_code:
        problems.append(
            f"measures.total_code ({declared_code}) != sum over units ({summed_code}) "
            "— code denominator is out of sync with the unit list."
        )

    if BUILD_CFG.exists() and declared_code:
        try:
            cfg = json.loads(BUILD_CFG.read_text(encoding="utf-8"))
            target_code = 0
            target_data = 0
            for unit in cfg.get("units", []) or []:
                target_code += mint(unit.get("code_size", 0))
                data_size = mint(unit.get("data_size", 0))
                name = str(unit.get("name", "")).lower()
                obj = str(unit.get("object", "")).lower()
                if data_size and "bss" not in name and "bss" not in obj:
                    target_data += data_size
            if target_code and declared_code != target_code:
                problems.append(
                    f"measures.total_code ({declared_code}) != dtk target code "
                    f"size ({target_code}). Regenerate report.json with "
                    "tools/gen_decomp_report.py."
                )
            declared_data = mint(measures.get("total_data", 0))
            if target_data and declared_data and declared_data != target_data:
                problems.append(
                    f"measures.total_data ({declared_data}) != dtk loadable "
                    f"non-BSS data size ({target_data}). Regenerate report.json "
                    "with tools/gen_decomp_report.py."
                )
        except (OSError, ValueError) as exc:
            problems.append(f"could not read build config for code size: {exc}")

    # 2b) The decomp.dev report must carry the non-code loadable data
    #     denominator, otherwise the second Code/Data progress bar disappears.
    total_data = mint(measures.get("total_data", 0))
    matched_data = mint(measures.get("matched_data", 0))
    complete_data = mint(measures.get("complete_data", 0))
    if total_data <= 0:
        problems.append(
            "measures.total_data is missing or zero — report.json will not "
            "render the decomp.dev Data progress bar."
        )
    if matched_data > total_data:
        problems.append(
            f"measures.matched_data ({matched_data}) exceeds total_data ({total_data})."
        )
    if complete_data > total_data:
        problems.append(
            f"measures.complete_data ({complete_data}) exceeds total_data ({total_data})."
        )
    if matched_data or complete_data:
        if not DATA_PROGRESS.exists():
            problems.append(
                "report.json claims matched/complete data bytes but "
                "config/GC6E01/data_progress.json is missing."
            )
        else:
            try:
                data_progress = json.loads(DATA_PROGRESS.read_text(encoding="utf-8"))
                seen = set()
                manifest_total = 0
                for item in data_progress.get("matched", []) or []:
                    key = (
                        item.get("section"),
                        item.get("start"),
                        item.get("object"),
                        item.get("source_path"),
                    )
                    if key in seen:
                        continue
                    seen.add(key)
                    manifest_total += mint(item.get("size", 0))
                if manifest_total != matched_data or manifest_total != complete_data:
                    problems.append(
                        "data_progress.json total does not match report.json "
                        f"(manifest={manifest_total}, matched_data={matched_data}, "
                        f"complete_data={complete_data})."
                    )
            except (OSError, ValueError) as exc:
                problems.append(f"could not read data_progress.json: {exc}")

            # Public CI generally lacks ROM-derived split objects. When the
            # local verifier prerequisites are available, require byte/reloc
            # proof for every manifest entry.
            if BUILD_CFG.exists() and OBJCOPY.exists() and DATA_VERIFIER.exists():
                verify = subprocess.run(
                    [sys.executable, "tools/verify_data_progress.py"],
                    cwd=ROOT,
                    capture_output=True,
                    text=True,
                )
                if verify.returncode != 0:
                    problems.append(
                        "data progress byte/reloc verification failed:\n"
                        + (verify.stdout + verify.stderr).strip()
                    )

    # 2c) Matched code/functions must represent active REAL_C only. Active asm
    #     wrappers and no-source split asm may be ROM-reproducible, but they are
    #     not decompiled C and must not contribute to function/code match.
    try:
        sys.path.insert(0, str(ROOT / "tools" / "decomp_work"))
        import progress2  # type: ignore

        _, fn2class = progress2.classify_all()
        non_real_matches = []
        for unit in units:
            for fn in unit.get("functions", []) or []:
                if mfloat(fn.get("fuzzy_match_percent", 0)) >= MATCH:
                    name = fn.get("name", "")
                    cls = fn2class.get(name, "NO_SOURCE")
                    if cls != "REAL_C":
                        non_real_matches.append(f"{name}:{cls}")
        if non_real_matches:
            problems.append(
                "report.json marks non-REAL_C functions as matched: "
                + ", ".join(non_real_matches[:20])
                + (" ..." if len(non_real_matches) > 20 else "")
            )
    except Exception as exc:  # noqa: BLE001
        problems.append(f"could not classify source functions for real-C match check: {exc}")

    fuzzy = mfloat(measures.get("fuzzy_match_percent", 0))
    if not 0.0 <= fuzzy <= 100.0:
        problems.append(f"measures.fuzzy_match_percent out of range: {fuzzy}")

    # 3) Phantom double-count detection. A band/scratch phantom is a COPY of a real
    #    TU, so it carries BOTH the same (total, matched) counts AND (nearly) the same
    #    function set. Require both signals: the counts are a cheap pre-filter, the
    #    function-set overlap confirms it is genuinely the same TU. This avoids two
    #    false positives: (a) different TUs that share counts by coincidence
    #    (gs_task and people.c can both be 49/53), and (b) pre-existing near-duplicate
    #    measurement units whose counts already differ (gs_field_world / gs_render_w2).
    by_sig: dict[tuple[int, int], list[tuple[str, frozenset]]] = {}
    for u in units:
        m = u.get("measures", {}) or {}
        sig = (int(m.get("total_functions", 0) or 0), int(m.get("matched_functions", 0) or 0))
        if sig[0] < 50:
            continue
        names = frozenset(f.get("name", "") for f in (u.get("functions", []) or []))
        for prev_name, prev_set in by_sig.get(sig, []):
            union = len(names | prev_set)
            jaccard = (len(names & prev_set) / union) if union else 0.0
            if jaccard >= 0.8:
                problems.append(
                    f"duplicate unit signature {sig} with {jaccard:.0%} function-set "
                    f"overlap shared by '{prev_name}' and '{u.get('name')}' — "
                    "likely a double-counted TU."
                )
                break
        by_sig.setdefault(sig, []).append((u.get("name", "?"), names))

    # 4) If checking the committed root report, also require the README and
    #    agent-lane progress.json to be synchronized with it.
    if path.resolve() == (ROOT / "report.json").resolve():
        sync = subprocess.run(
            [sys.executable, "tools/sync_progress_metadata.py", "--check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if sync.returncode != 0:
            problems.append(
                "progress metadata is stale relative to report.json:\n"
                + (sync.stdout + sync.stderr).strip()
            )

    if problems:
        print("report-sanity: FAIL", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        return 1

    print(
        f"report-sanity: OK ({len(units)} units, "
        f"total_functions={declared or summed}, "
        f"code={measures.get('matched_code', 0)}/{declared_code or summed_code} "
        f"({measures.get('matched_code_percent', 0):.2f}%), "
        f"data={matched_data}/{total_data})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
