#!/usr/bin/env python3
"""check_report_sanity.py - guard report.json against phantom/scratch units.

The decomp.dev progress metric (report.json) is generated by scanning every
base object in build/GC6E01/base/. The band harness + band_integrate.py drop
TRANSIENT scratch objects there (band_*, *_integrated, _int_*, _evt_*, cs_*).
If those get counted as real translation units they become PHANTOM units that
duplicate a real TU and inflate total_functions — which silently dropped the
published code% from ~53% to ~44% on 2026-06-16 (the band_trainer_integrated /
manual_integrated / band_mtool incident: +783 phantom functions) even though
the DOL still byte-matched the ROM.

This check fails CI if report.json contains any scratch-pattern unit, so a
polluted report can never be merged again. It also cross-checks that the
top-level total_functions equals the sum over units (no hidden inflation).

Usage:  python tools/check_report_sanity.py [path/to/report.json]
Exit 0 = clean, 1 = violation.
"""
import json
import re
import sys
from pathlib import Path

# Keep this pattern in sync with tools/progress.py:SKIP_BASE_SCRATCH.
SCRATCH = re.compile(
    r"^(band_|manual_integrated|_int_|_evt_|cs_)|_integrated$|__a_fn_",
    re.IGNORECASE,
)


def main(argv: list[str]) -> int:
    path = Path(argv[1]) if len(argv) > 1 else Path("report.json")
    if not path.exists():
        print(f"report-sanity: {path} not found — nothing to check", file=sys.stderr)
        return 0

    report = json.loads(path.read_text(encoding="utf-8"))
    units = report.get("units", []) or []
    measures = report.get("measures", {}) or {}

    problems: list[str] = []

    # 1) No scratch/phantom units.
    scratch = [u.get("name", "?") for u in units if SCRATCH.search(u.get("name", ""))]
    if scratch:
        problems.append(
            "phantom/scratch units present in report.json (band-harness leakage): "
            + ", ".join(sorted(scratch))
            + "\n  Fix: remove build/GC6E01/base/<that>.o and regenerate "
            "(tools/progress.py skips these via SKIP_BASE_SCRATCH)."
        )

    # 2) Top-level total_functions must equal the sum over units (no hidden inflation).
    def usum(key: str) -> int:
        total = 0
        for u in units:
            v = (u.get("measures", {}) or {}).get(key, 0)
            try:
                total += int(float(v))
            except (TypeError, ValueError):
                pass
        return total

    summed = usum("total_functions")
    declared = int(measures.get("total_functions", 0) or 0)
    if declared and summed and declared != summed:
        problems.append(
            f"measures.total_functions ({declared}) != sum over units ({summed}) "
            "— aggregate is out of sync with the unit list."
        )

    # 2b) Version 2 fields drive decomp.dev's matched-vs-linked two-bar UI.
    version = int(report.get("version", 0) or 0)
    if version != 2:
        problems.append(
            f"report.version is {version}; expected objdiff report v2 for "
            "complete/linked unit fields."
        )

    for key in (
        "total_code", "matched_code", "complete_code",
        "total_data", "matched_data", "complete_data",
        "total_units", "complete_units",
    ):
        summed_key = usum(key)
        declared_key = int(float(measures.get(key, 0) or 0))
        if summed_key != declared_key:
            problems.append(
                f"measures.{key} ({declared_key}) != sum over units "
                f"({summed_key}) — aggregate is out of sync."
            )

    # 3) Phantom double-count detection. A band/scratch phantom is a COPY of a real
    #    TU, so it carries BOTH the same (total, matched) counts AND (nearly) the same
    #    function set. Require both signals: the counts are a cheap pre-filter, the
    #    function-set overlap confirms it is genuinely the same TU. This avoids two
    #    false positives: (a) different TUs that share counts by coincidence
    #    (gs_task and people.c can both be 49/53), and (b) pre-existing near-duplicate
    #    measurement units whose counts already differ (gs_field_world / gs_render_w2).
    by_sig: dict[tuple[int, int], list[tuple[str, frozenset]]] = {}
    for u in units:
        m = u.get("measures", {}) or {}
        sig = (int(m.get("total_functions", 0) or 0), int(m.get("matched_functions", 0) or 0))
        if sig[0] < 50:
            continue
        names = frozenset(f.get("name", "") for f in (u.get("functions", []) or []))
        for prev_name, prev_set in by_sig.get(sig, []):
            union = len(names | prev_set)
            jaccard = (len(names & prev_set) / union) if union else 0.0
            if jaccard >= 0.8:
                problems.append(
                    f"duplicate unit signature {sig} with {jaccard:.0%} function-set "
                    f"overlap shared by '{prev_name}' and '{u.get('name')}' — "
                    "likely a double-counted TU."
                )
                break
        by_sig.setdefault(sig, []).append((u.get("name", "?"), names))

    if problems:
        print("report-sanity: FAIL", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        return 1

    print(
        f"report-sanity: OK ({len(units)} units, "
        f"total_functions={declared or summed}, "
        f"code%={measures.get('matched_code_percent', 0):.2f})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
